// ===== БАЗА 300 ПОПУЛЯРНЫХ ФРАЗ НА АНГЛИЙСКОМ =====
const commonPhrases = [
    // ===== ПРИВЕТСТВИЕ И ВЕЖЛИВОСТЬ (1-20) =====
    { eng: "Hello!", ru: "Привет!", category: "Приветствие" },
    { eng: "Hi!", ru: "Привет!", category: "Приветствие" },
    { eng: "Good morning!", ru: "Доброе утро!", category: "Приветствие" },
    { eng: "Good afternoon!", ru: "Добрый день!", category: "Приветствие" },
    { eng: "Good evening!", ru: "Добрый вечер!", category: "Приветствие" },
    { eng: "Good night!", ru: "Спокойной ночи!", category: "Приветствие" },
    { eng: "How are you?", ru: "Как дела?", category: "Приветствие" },
    { eng: "How's it going?", ru: "Как успехи?", category: "Приветствие" },
    { eng: "What's up?", ru: "Как дела? (неформально)", category: "Приветствие" },
    { eng: "What's new?", ru: "Что нового?", category: "Приветствие" },
    { eng: "Nice to meet you!", ru: "Приятно познакомиться!", category: "Приветствие" },
    { eng: "Pleased to meet you!", ru: "Рад познакомиться!", category: "Приветствие" },
    { eng: "How do you do?", ru: "Здравствуйте! (официально)", category: "Приветствие" },
    { eng: "Long time no see!", ru: "Давно не виделись!", category: "Приветствие" },
    { eng: "It's been a while!", ru: "Прошло много времени!", category: "Приветствие" },
    { eng: "See you later!", ru: "Увидимся позже!", category: "Приветствие" },
    { eng: "See you tomorrow!", ru: "Увидимся завтра!", category: "Приветствие" },
    { eng: "See you soon!", ru: "До скорой встречи!", category: "Приветствие" },
    { eng: "Bye!", ru: "Пока!", category: "Приветствие" },
    { eng: "Goodbye!", ru: "До свидания!", category: "Приветствие" },
    
    // ===== ВЕЖЛИВОСТЬ (21-35) =====
    { eng: "Please!", ru: "Пожалуйста!", category: "Приветствие" },
    { eng: "Thank you!", ru: "Спасибо!", category: "Приветствие" },
    { eng: "Thanks a lot!", ru: "Большое спасибо!", category: "Приветствие" },
    { eng: "Thank you very much!", ru: "Огромное спасибо!", category: "Приветствие" },
    { eng: "You're welcome!", ru: "Пожалуйста! (в ответ на спасибо)", category: "Приветствие" },
    { eng: "Excuse me!", ru: "Извините!", category: "Приветствие" },
    { eng: "I'm sorry!", ru: "Мне жаль!", category: "Приветствие" },
    { eng: "Sorry!", ru: "Прости!", category: "Приветствие" },
    { eng: "No problem!", ru: "Без проблем!", category: "Приветствие" },
    { eng: "Don't worry!", ru: "Не волнуйтесь!", category: "Приветствие" },
    { eng: "Take care!", ru: "Береги себя!", category: "Приветствие" },
    { eng: "Have a nice day!", ru: "Хорошего дня!", category: "Приветствие" },
    { eng: "Have a good weekend!", ru: "Хороших выходных!", category: "Приветствие" },
    { eng: "Enjoy!", ru: "Наслаждайтесь!", category: "Приветствие" },
    { eng: "Bless you!", ru: "Будьте здоровы! (когда чихают)", category: "Приветствие" },
    
    // ===== ПОВСЕДНЕВНЫЕ ФРАЗЫ (36-70) =====
    { eng: "What time is it?", ru: "Который час?", category: "Повседневные" },
    { eng: "It's 10 o'clock.", ru: "10 часов.", category: "Повседневные" },
    { eng: "It's half past five.", ru: "Половина шестого.", category: "Повседневные" },
    { eng: "It's quarter to six.", ru: "Без пятнадцати шесть.", category: "Повседневные" },
    { eng: "What's the date today?", ru: "Какое сегодня число?", category: "Повседневные" },
    { eng: "What day is it today?", ru: "Какой сегодня день?", category: "Повседневные" },
    { eng: "What's the weather like?", ru: "Какая погода?", category: "Повседневные" },
    { eng: "It's sunny today.", ru: "Сегодня солнечно.", category: "Повседневные" },
    { eng: "It's raining.", ru: "Идёт дождь.", category: "Повседневные" },
    { eng: "It's snowing.", ru: "Идёт снег.", category: "Повседневные" },
    { eng: "It's cloudy.", ru: "Облачно.", category: "Повседневные" },
    { eng: "It's windy.", ru: "Ветрено.", category: "Повседневные" },
    { eng: "It's cold outside.", ru: "На улице холодно.", category: "Повседневные" },
    { eng: "It's hot today.", ru: "Сегодня жарко.", category: "Повседневные" },
    { eng: "It's warm.", ru: "Тепло.", category: "Повседневные" },
    { eng: "It's freezing!", ru: "Морозно!", category: "Повседневные" },
    { eng: "I'm tired.", ru: "Я устал.", category: "Повседневные" },
    { eng: "I'm exhausted.", ru: "Я истощён.", category: "Повседневные" },
    { eng: "I'm sleepy.", ru: "Я хочу спать.", category: "Повседневные" },
    { eng: "I'm hungry.", ru: "Я голоден.", category: "Повседневные" },
    { eng: "I'm starving!", ru: "Я умираю с голоду!", category: "Повседневные" },
    { eng: "I'm thirsty.", ru: "Я хочу пить.", category: "Повседневные" },
    { eng: "I'm busy.", ru: "Я занят.", category: "Повседневные" },
    { eng: "I'm in a hurry.", ru: "Я спешу.", category: "Повседневные" },
    { eng: "I'm late.", ru: "Я опаздываю.", category: "Повседневные" },
    { eng: "I'm ready.", ru: "Я готов.", category: "Повседневные" },
    { eng: "I'm not ready.", ru: "Я не готов.", category: "Повседневные" },
    { eng: "I'm sure.", ru: "Я уверен.", category: "Повседневные" },
    { eng: "I'm not sure.", ru: "Я не уверен.", category: "Повседневные" },
    { eng: "That's great!", ru: "Это здорово!", category: "Повседневные" },
    { eng: "That's terrible!", ru: "Это ужасно!", category: "Повседневные" },
    { eng: "That's amazing!", ru: "Это потрясающе!", category: "Повседневные" },
    { eng: "That's awesome!", ru: "Это классно!", category: "Повседневные" },
    { eng: "That's too bad.", ru: "Это очень плохо.", category: "Повседневные" },
    { eng: "I don't know.", ru: "Я не знаю.", category: "Повседневные" },
    
    // ===== ПОНИМАНИЕ И КОММУНИКАЦИЯ (71-90) =====
    { eng: "I understand.", ru: "Я понимаю.", category: "Повседневные" },
    { eng: "I don't understand.", ru: "Я не понимаю.", category: "Повседневные" },
    { eng: "Please speak slower.", ru: "Пожалуйста, говорите медленнее.", category: "Повседневные" },
    { eng: "Could you repeat that?", ru: "Не могли бы вы повторить?", category: "Повседневные" },
    { eng: "What does it mean?", ru: "Что это значит?", category: "Повседневные" },
    { eng: "How do you say this in English?", ru: "Как это сказать по-английски?", category: "Повседневные" },
    { eng: "Can you help me?", ru: "Можете мне помочь?", category: "Повседневные" },
    { eng: "Of course!", ru: "Конечно!", category: "Повседневные" },
    { eng: "No problem!", ru: "Без проблем!", category: "Повседневные" },
    { eng: "Absolutely!", ru: "Абсолютно!", category: "Повседневные" },
    { eng: "Definitely!", ru: "Определённо!", category: "Повседневные" },
    { eng: "Maybe.", ru: "Возможно.", category: "Повседневные" },
    { eng: "Probably.", ru: "Вероятно.", category: "Повседневные" },
    { eng: "I think so.", ru: "Я так думаю.", category: "Повседневные" },
    { eng: "I hope so.", ru: "Я надеюсь.", category: "Повседневные" },
    { eng: "I guess so.", ru: "Наверное.", category: "Повседневные" },
    { eng: "I agree.", ru: "Я согласен.", category: "Повседневные" },
    { eng: "I disagree.", ru: "Я не согласен.", category: "Повседневные" },
    { eng: "You're right.", ru: "Ты прав.", category: "Повседневные" },
    { eng: "You're wrong.", ru: "Ты не прав.", category: "Повседневные" },
    
    // ===== РАБОТА И УЧЁБА (91-115) =====
    { eng: "I'm going to work.", ru: "Я иду на работу.", category: "Работа" },
    { eng: "I'm going to school.", ru: "Я иду в школу.", category: "Работа" },
    { eng: "I work at an office.", ru: "Я работаю в офисе.", category: "Работа" },
    { eng: "I work from home.", ru: "Я работаю из дома.", category: "Работа" },
    { eng: "What do you do?", ru: "Кем вы работаете?", category: "Работа" },
    { eng: "What's your job?", ru: "Какая у вас работа?", category: "Работа" },
    { eng: "I'm a teacher.", ru: "Я учитель.", category: "Работа" },
    { eng: "I'm a student.", ru: "Я студент.", category: "Работа" },
    { eng: "I'm a doctor.", ru: "Я врач.", category: "Работа" },
    { eng: "I'm an engineer.", ru: "Я инженер.", category: "Работа" },
    { eng: "I'm learning English.", ru: "Я учу английский.", category: "Работа" },
    { eng: "I'm studying at university.", ru: "Я учусь в университете.", category: "Работа" },
    { eng: "I need to study.", ru: "Мне нужно учиться.", category: "Работа" },
    { eng: "I have a test tomorrow.", ru: "У меня завтра тест.", category: "Работа" },
    { eng: "What time do you finish?", ru: "Во сколько вы заканчиваете?", category: "Работа" },
    { eng: "I work from 9 to 5.", ru: "Я работаю с 9 до 5.", category: "Работа" },
    { eng: "I have a meeting.", ru: "У меня встреча.", category: "Работа" },
    { eng: "I'm on vacation.", ru: "Я в отпуске.", category: "Работа" },
    { eng: "I have a day off.", ru: "У меня выходной.", category: "Работа" },
    { eng: "Can I help you?", ru: "Могу я вам помочь?", category: "Работа" },
    { eng: "Thank you for your help.", ru: "Спасибо за вашу помощь.", category: "Работа" },
    { eng: "I appreciate it.", ru: "Я ценю это.", category: "Работа" },
    { eng: "I'm looking for a job.", ru: "Я ищу работу.", category: "Работа" },
    { eng: "I'm unemployed.", ru: "Я безработный.", category: "Работа" },
    { eng: "I'm retired.", ru: "Я на пенсии.", category: "Работа" },
    
    // ===== ПУТЕШЕСТВИЯ (116-145) =====
    { eng: "Where is the nearest hotel?", ru: "Где ближайший отель?", category: "Путешествия" },
    { eng: "How can I get to the airport?", ru: "Как мне добраться до аэропорта?", category: "Путешествия" },
    { eng: "I'm looking for the train station.", ru: "Я ищу вокзал.", category: "Путешествия" },
    { eng: "Is there a bus stop nearby?", ru: "Здесь есть автобусная остановка?", category: "Путешествия" },
    { eng: "How much is a ticket?", ru: "Сколько стоит билет?", category: "Путешествия" },
    { eng: "I'd like a ticket to London.", ru: "Мне нужен билет до Лондона.", category: "Путешествия" },
    { eng: "Where is the restroom?", ru: "Где туалет?", category: "Путешествия" },
    { eng: "Excuse me, where is the museum?", ru: "Извините, где находится музей?", category: "Путешествия" },
    { eng: "Is it far from here?", ru: "Это далеко отсюда?", category: "Путешествия" },
    { eng: "It's near the park.", ru: "Это рядом с парком.", category: "Путешествия" },
    { eng: "Can you show me on the map?", ru: "Можете показать на карте?", category: "Путешествия" },
    { eng: "I'm lost.", ru: "Я заблудился.", category: "Путешествия" },
    { eng: "I need a taxi.", ru: "Мне нужно такси.", category: "Путешествия" },
    { eng: "How long does it take?", ru: "Сколько времени это займёт?", category: "Путешествия" },
    { eng: "Have a good trip!", ru: "Хорошей поездки!", category: "Путешествия" },
    { eng: "Where are you going?", ru: "Куда вы едете?", category: "Путешествия" },
    { eng: "I'm going to Paris.", ru: "Я еду в Париж.", category: "Путешествия" },
    { eng: "I'm on holiday.", ru: "Я в отпуске.", category: "Путешествия" },
    { eng: "What's the best way to get there?", ru: "Как лучше туда добраться?", category: "Путешествия" },
    { eng: "Can I get a discount?", ru: "Можно получить скидку?", category: "Путешествия" },
    { eng: "Do you accept credit cards?", ru: "Вы принимаете кредитные карты?", category: "Путешествия" },
    { eng: "What time does the train leave?", ru: "Во сколько отправляется поезд?", category: "Путешествия" },
    { eng: "What time does it arrive?", ru: "Во сколько прибывает?", category: "Путешествия" },
    { eng: "Is there a direct flight?", ru: "Есть прямой рейс?", category: "Путешествия" },
    { eng: "I'd like to book a room.", ru: "Я хотел бы забронировать номер.", category: "Путешествия" },
    { eng: "Do you have any available rooms?", ru: "У вас есть свободные номера?", category: "Путешествия" },
    { eng: "Can I see the room?", ru: "Можно посмотреть номер?", category: "Путешествия" },
    { eng: "I'll take the room.", ru: "Я беру номер.", category: "Путешествия" },
    { eng: "Check-in, please.", ru: "Регистрация, пожалуйста.", category: "Путешествия" },
    { eng: "Check-out, please.", ru: "Выезд, пожалуйста.", category: "Путешествия" },
    
    // ===== ПОКУПКИ (146-170) =====
    { eng: "How much is it?", ru: "Сколько это стоит?", category: "Покупки" },
    { eng: "It's too expensive.", ru: "Это слишком дорого.", category: "Покупки" },
    { eng: "Do you have a discount?", ru: "У вас есть скидка?", category: "Покупки" },
    { eng: "I'd like to buy this.", ru: "Я хотел бы это купить.", category: "Покупки" },
    { eng: "Can I try it on?", ru: "Можно примерить?", category: "Покупки" },
    { eng: "What size is this?", ru: "Какой это размер?", category: "Покупки" },
    { eng: "Do you have a smaller size?", ru: "У вас есть размер поменьше?", category: "Покупки" },
    { eng: "I'll take it.", ru: "Я это беру.", category: "Покупки" },
    { eng: "Can I pay by card?", ru: "Можно оплатить картой?", category: "Покупки" },
    { eng: "Here is your change.", ru: "Ваша сдача.", category: "Покупки" },
    { eng: "Do you have this in red?", ru: "У вас есть это в красном?", category: "Покупки" },
    { eng: "Can I get a receipt?", ru: "Можно получить чек?", category: "Покупки" },
    { eng: "Is there a cheaper option?", ru: "Есть вариант подешевле?", category: "Покупки" },
    { eng: "I'm just looking.", ru: "Я просто смотрю.", category: "Покупки" },
    { eng: "That's a good price!", ru: "Это хорошая цена!", category: "Покупки" },
    { eng: "It's on sale.", ru: "Это по скидке.", category: "Покупки" },
    { eng: "Where is the cash desk?", ru: "Где касса?", category: "Покупки" },
    { eng: "Do you have a bag?", ru: "У вас есть пакет?", category: "Покупки" },
    { eng: "Can I get a refund?", ru: "Можно вернуть деньги?", category: "Покупки" },
    { eng: "What's the exchange rate?", ru: "Какой курс обмена?", category: "Покупки" },
    { eng: "I need to exchange money.", ru: "Мне нужно обменять деньги.", category: "Покупки" },
    { eng: "Where is the nearest bank?", ru: "Где ближайший банк?", category: "Покупки" },
    { eng: "What time do you open?", ru: "Во сколько вы открываетесь?", category: "Покупки" },
    { eng: "What time do you close?", ru: "Во сколько вы закрываетесь?", category: "Покупки" },
    { eng: "Is there a sale?", ru: "Есть распродажа?", category: "Покупки" },
    
    // ===== ЭМОЦИИ И ЧУВСТВА (171-200) =====
    { eng: "I'm happy.", ru: "Я счастлив.", category: "Эмоции" },
    { eng: "I'm very happy!", ru: "Я очень счастлив!", category: "Эмоции" },
    { eng: "I'm sad.", ru: "Мне грустно.", category: "Эмоции" },
    { eng: "I'm angry.", ru: "Я злой.", category: "Эмоции" },
    { eng: "I'm excited!", ru: "Я в восторге!", category: "Эмоции" },
    { eng: "I'm worried.", ru: "Я беспокоюсь.", category: "Эмоции" },
    { eng: "I'm surprised!", ru: "Я удивлён!", category: "Эмоции" },
    { eng: "I'm scared.", ru: "Мне страшно.", category: "Эмоции" },
    { eng: "I'm nervous.", ru: "Я нервничаю.", category: "Эмоции" },
    { eng: "I'm confused.", ru: "Я запутан.", category: "Эмоции" },
    { eng: "I'm embarrassed.", ru: "Мне стыдно.", category: "Эмоции" },
    { eng: "I'm proud of you!", ru: "Я горжусь тобой!", category: "Эмоции" },
    { eng: "I love you!", ru: "Я тебя люблю!", category: "Эмоции" },
    { eng: "I like it!", ru: "Мне это нравится!", category: "Эмоции" },
    { eng: "I hate it.", ru: "Я это ненавижу.", category: "Эмоции" },
    { eng: "It's amazing!", ru: "Это потрясающе!", category: "Эмоции" },
    { eng: "It's wonderful!", ru: "Это замечательно!", category: "Эмоции" },
    { eng: "It's fantastic!", ru: "Это фантастика!", category: "Эмоции" },
    { eng: "I feel great!", ru: "Я чувствую себя отлично!", category: "Эмоции" },
    { eng: "I feel terrible.", ru: "Я чувствую себя ужасно.", category: "Эмоции" },
    { eng: "I'm bored.", ru: "Мне скучно.", category: "Эмоции" },
    { eng: "I'm disappointed.", ru: "Я разочарован.", category: "Эмоции" },
    { eng: "I'm relieved.", ru: "Я облегчён.", category: "Эмоции" },
    { eng: "I'm grateful.", ru: "Я благодарен.", category: "Эмоции" },
    { eng: "I'm thankful.", ru: "Я благодарен.", category: "Эмоции" },
    { eng: "I'm sorry to hear that.", ru: "Мне жаль это слышать.", category: "Эмоции" },
    { eng: "What a pity!", ru: "Как жалко!", category: "Эмоции" },
    { eng: "What a shame!", ru: "Какой позор!", category: "Эмоции" },
    { eng: "How wonderful!", ru: "Как замечательно!", category: "Эмоции" },
    { eng: "How terrible!", ru: "Как ужасно!", category: "Эмоции" },
    
    // ===== ЕДА И НАПИТКИ (201-225) =====
    { eng: "What would you like to eat?", ru: "Что бы вы хотели съесть?", category: "Еда" },
    { eng: "I'd like a cup of coffee.", ru: "Я бы хотел чашку кофе.", category: "Еда" },
    { eng: "Tea, please.", ru: "Чай, пожалуйста.", category: "Еда" },
    { eng: "What's on the menu?", ru: "Что есть в меню?", category: "Еда" },
    { eng: "I'd like the bill, please.", ru: "Счёт, пожалуйста.", category: "Еда" },
    { eng: "The food is delicious!", ru: "Еда восхитительна!", category: "Еда" },
    { eng: "I'm a vegetarian.", ru: "Я вегетарианец.", category: "Еда" },
    { eng: "Do you have any recommendations?", ru: "У вас есть какие-либо рекомендации?", category: "Еда" },
    { eng: "I'll have the same.", ru: "Я возьму то же самое.", category: "Еда" },
    { eng: "Can I have some water?", ru: "Можно мне воды?", category: "Еда" },
    { eng: "It's very tasty!", ru: "Очень вкусно!", category: "Еда" },
    { eng: "I don't like spicy food.", ru: "Я не люблю острую еду.", category: "Еда" },
    { eng: "Is there sugar in it?", ru: "В этом есть сахар?", category: "Еда" },
    { eng: "Can I order takeout?", ru: "Можно заказать еду с собой?", category: "Еда" },
    { eng: "Enjoy your meal!", ru: "Приятного аппетита!", category: "Еда" },
    { eng: "Can I have a menu?", ru: "Можно мне меню?", category: "Еда" },
    { eng: "What's the special today?", ru: "Что сегодня особенного?", category: "Еда" },
    { eng: "I'd like to reserve a table.", ru: "Я хотел бы забронировать столик.", category: "Еда" },
    { eng: "I'm allergic to nuts.", ru: "У меня аллергия на орехи.", category: "Еда" },
    { eng: "Is this gluten-free?", ru: "Это без глютена?", category: "Еда" },
    { eng: "Could I have more bread?", ru: "Можно мне ещё хлеба?", category: "Еда" },
    { eng: "The service is great!", ru: "Обслуживание отличное!", category: "Еда" },
    { eng: "The food was amazing!", ru: "Еда была потрясающей!", category: "Еда" },
    { eng: "I'm full.", ru: "Я сыт.", category: "Еда" },
    { eng: "That was delicious!", ru: "Было очень вкусно!", category: "Еда" },
    
    // ===== ЗДОРОВЬЕ (226-240) =====
    { eng: "I'm feeling sick.", ru: "Я чувствую себя больным.", category: "Повседневные" },
    { eng: "I have a headache.", ru: "У меня болит голова.", category: "Повседневные" },
    { eng: "I have a cold.", ru: "Я простудился.", category: "Повседневные" },
    { eng: "I have a fever.", ru: "У меня температура.", category: "Повседневные" },
    { eng: "I need a doctor.", ru: "Мне нужен врач.", category: "Повседневные" },
    { eng: "Where is the pharmacy?", ru: "Где аптека?", category: "Повседневные" },
    { eng: "I need some medicine.", ru: "Мне нужно лекарство.", category: "Повседневные" },
    { eng: "I feel better now.", ru: "Теперь я чувствую себя лучше.", category: "Повседневные" },
    { eng: "I feel worse.", ru: "Я чувствую себя хуже.", category: "Повседневные" },
    { eng: "Take this medicine.", ru: "Примите это лекарство.", category: "Повседневные" },
    { eng: "Get well soon!", ru: "Поправляйся скорее!", category: "Повседневные" },
    { eng: "I need to see a dentist.", ru: "Мне нужно к стоматологу.", category: "Повседневные" },
    { eng: "It hurts here.", ru: "Здесь болит.", category: "Повседневные" },
    { eng: "I have a toothache.", ru: "У меня болит зуб.", category: "Повседневные" },
    { eng: "I feel dizzy.", ru: "У меня кружится голова.", category: "Повседневные" },
    
    // ===== ТЕХНОЛОГИИ (241-250) =====
    { eng: "What's your phone number?", ru: "Какой у вас номер телефона?", category: "Повседневные" },
    { eng: "Can I use your phone?", ru: "Можно воспользоваться вашим телефоном?", category: "Повседневные" },
    { eng: "What's your email address?", ru: "Какой у вас адрес электронной почты?", category: "Повседневные" },
    { eng: "I'll send you an email.", ru: "Я пришлю вам письмо.", category: "Повседневные" },
    { eng: "Do you have Wi-Fi?", ru: "У вас есть Wi-Fi?", category: "Повседневные" },
    { eng: "What's the Wi-Fi password?", ru: "Какой пароль от Wi-Fi?", category: "Повседневные" },
    { eng: "I need to charge my phone.", ru: "Мне нужно зарядить телефон.", category: "Повседневные" },
    { eng: "Can you take a photo?", ru: "Можете сделать фото?", category: "Повседневные" },
    { eng: "I'll post it on social media.", ru: "Я опубликую это в соцсетях.", category: "Повседневные" },
    { eng: "Do you have an app for that?", ru: "У вас есть приложение для этого?", category: "Повседневные" },
    
    // ===== ДОПОЛНИТЕЛЬНЫЕ ФРАЗЫ (251-300) =====
    { eng: "What's your name?", ru: "Как вас зовут?", category: "Приветствие" },
    { eng: "My name is...", ru: "Меня зовут...", category: "Приветствие" },
    { eng: "Where are you from?", ru: "Откуда вы?", category: "Приветствие" },
    { eng: "I'm from Russia.", ru: "Я из России.", category: "Приветствие" },
    { eng: "How old are you?", ru: "Сколько вам лет?", category: "Приветствие" },
    { eng: "I'm 25 years old.", ru: "Мне 25 лет.", category: "Приветствие" },
    { eng: "Do you speak English?", ru: "Вы говорите по-английски?", category: "Приветствие" },
    { eng: "I speak a little English.", ru: "Я немного говорю по-английски.", category: "Приветствие" },
    { eng: "What do you like to do?", ru: "Что вы любите делать?", category: "Повседневные" },
    { eng: "I like reading books.", ru: "Я люблю читать книги.", category: "Повседневные" },
    { eng: "I like watching movies.", ru: "Я люблю смотреть фильмы.", category: "Повседневные" },
    { eng: "I like listening to music.", ru: "Я люблю слушать музыку.", category: "Повседневные" },
    { eng: "I like traveling.", ru: "Я люблю путешествовать.", category: "Повседневные" },
    { eng: "I like cooking.", ru: "Я люблю готовить.", category: "Повседневные" },
    { eng: "I like sports.", ru: "Я люблю спорт.", category: "Повседневные" },
    { eng: "Do you have any pets?", ru: "У вас есть домашние животные?", category: "Повседневные" },
    { eng: "I have a dog.", ru: "У меня есть собака.", category: "Повседневные" },
    { eng: "I have a cat.", ru: "У меня есть кошка.", category: "Повседневные" },
    { eng: "What's your favorite color?", ru: "Какой ваш любимый цвет?", category: "Повседневные" },
    { eng: "My favorite color is blue.", ru: "Мой любимый цвет - синий.", category: "Повседневные" },
    { eng: "What's your favorite food?", ru: "Какая ваша любимая еда?", category: "Еда" },
    { eng: "I love pizza!", ru: "Я обожаю пиццу!", category: "Еда" },
    { eng: "I love chocolate.", ru: "Я люблю шоколад.", category: "Еда" },
    { eng: "What's your hobby?", ru: "Какое у вас хобби?", category: "Повседневные" },
    { eng: "I like painting.", ru: "Я люблю рисовать.", category: "Повседневные" },
    { eng: "I like dancing.", ru: "Я люблю танцевать.", category: "Повседневные" },
    { eng: "I like singing.", ru: "Я люблю петь.", category: "Повседневные" },
    { eng: "I like playing guitar.", ru: "Я люблю играть на гитаре.", category: "Повседневные" },
    { eng: "I like photography.", ru: "Я люблю фотографировать.", category: "Повседневные" },
    { eng: "I like hiking.", ru: "Я люблю ходить в походы.", category: "Повседневные" },
    { eng: "I like swimming.", ru: "Я люблю плавать.", category: "Повседневные" },
    { eng: "I like cycling.", ru: "Я люблю кататься на велосипеде.", category: "Повседневные" },
    { eng: "I like running.", ru: "Я люблю бегать.", category: "Повседневные" },
    { eng: "I like yoga.", ru: "Я люблю йогу.", category: "Повседневные" },
    { eng: "I like meditation.", ru: "Я люблю медитацию.", category: "Повседневные" },
    { eng: "I like learning new things.", ru: "Я люблю узнавать новое.", category: "Повседневные" },
    { eng: "I like meeting new people.", ru: "Я люблю знакомиться с новыми людьми.", category: "Повседневные" },
    { eng: "I like spending time with friends.", ru: "Я люблю проводить время с друзьями.", category: "Повседневные" },
    { eng: "I like going to the cinema.", ru: "Я люблю ходить в кино.", category: "Повседневные" },
    { eng: "I like going to the theatre.", ru: "Я люблю ходить в театр.", category: "Повседневные" },
    { eng: "I like going to museums.", ru: "Я люблю ходить в музеи.", category: "Повседневные" },
    { eng: "I like going to concerts.", ru: "Я люблю ходить на концерты.", category: "Повседневные" },
    { eng: "I like walking in the park.", ru: "Я люблю гулять в парке.", category: "Повседневные" },
    { eng: "I like reading newspapers.", ru: "Я люблю читать газеты.", category: "Повседневные" },
    { eng: "I like watching TV.", ru: "Я люблю смотреть телевизор.", category: "Повседневные" },
    { eng: "I like playing video games.", ru: "Я люблю играть в видеоигры.", category: "Повседневные" },
    { eng: "I like doing sports.", ru: "Я люблю заниматься спортом.", category: "Повседневные" },
    { eng: "I like going to the gym.", ru: "Я люблю ходить в спортзал.", category: "Повседневные" },
    { eng: "I like drinking coffee.", ru: "Я люблю пить кофе.", category: "Еда" },
    { eng: "I like drinking tea.", ru: "Я люблю пить чай.", category: "Еда" }
];

// ===== ДОБАВЛЯЕМ ID КАЖДОЙ ФРАЗЕ =====
commonPhrases.forEach((p, index) => {
    p.id = index + 1;
});

// ===== АВТОМАТИЧЕСКОЕ СОЗДАНИЕ КАТЕГОРИЙ =====
function getCategories() {
    const categories = new Set();
    commonPhrases.forEach(p => categories.add(p.category));
    
    const emojiMap = {
        'Приветствие': '👋',
        'Повседневные': '🏠',
        'Работа': '💼',
        'Путешествия': '✈️',
        'Покупки': '🛍️',
        'Эмоции': '😊',
        'Еда': '🍽️'
    };
    
    const result = [{ id: 'all', name: 'Все', emoji: '📚' }];
    categories.forEach(cat => {
        result.push({
            id: cat,
            name: cat,
            emoji: emojiMap[cat] || '📌'
        });
    });
    return result;
}

// ===== ГЛОБАЛЬНАЯ ПЕРЕМЕННАЯ ДЛЯ КАТЕГОРИЙ =====
const phraseCategories = getCategories();

// ===== ПРОВЕРКА ЗАГРУЗКИ =====
console.log('✅ phrases.js загружен! Фраз:', commonPhrases.length);
console.log('📂 Категории:', phraseCategories.map(c => c.name).join(', '));