// quiz.js — большой массив вопросов с ответами для тренажёра
// Каждый вопрос: { q, options, correct, hint, category }
// correct — индекс правильного ответа (0-3)

const quizCategories = [
    { id: 'all',        emoji: '📚', name: 'Все' },
    { id: 'verbs',      emoji: '⚡', name: 'Глаголы' },
    { id: 'irregular',  emoji: '🔀', name: 'Неправильные' },
    { id: 'preps',      emoji: '🧭', name: 'Предлоги' },
    { id: 'prefixes',   emoji: '🔤', name: 'Приставки' },
    { id: 'roots',      emoji: '🧱', name: 'Корни' },
    { id: 'phrases',    emoji: '💬', name: 'Фразы' },
    { id: 'magic',      emoji: '🎩', name: 'Магия' }
];

const quizQuestions = [
    // ═══════ НЕПРАВИЛЬНЫЕ ГЛАГОЛЫ (V2/V3) — 30 вопросов ═══════
    { category: 'irregular', q: 'Какая V2 (Past Simple) у глагола <b>go</b>?', options: ['goed', 'went', 'gone', 'going'], correct: 1, hint: 'go → went → gone' },
    { category: 'irregular', q: 'Какая V3 (Past Participle) у глагола <b>go</b>?', options: ['goed', 'went', 'gone', 'going'], correct: 2, hint: 'go → went → gone' },
    { category: 'irregular', q: 'Какая V2 у глагола <b>eat</b>?', options: ['eated', 'ate', 'eaten', 'eating'], correct: 1, hint: 'eat → ate → eaten' },
    { category: 'irregular', q: 'Какая V3 у глагола <b>eat</b>?', options: ['eated', 'ate', 'eaten', 'eating'], correct: 2, hint: 'eat → ate → eaten' },
    { category: 'irregular', q: 'Какая V2 у глагола <b>see</b>?', options: ['seed', 'saw', 'seen', 'seeing'], correct: 1, hint: 'see → saw → seen' },
    { category: 'irregular', q: 'Какая V3 у глагола <b>see</b>?', options: ['seed', 'saw', 'seen', 'seeing'], correct: 2, hint: 'see → saw → seen' },
    { category: 'irregular', q: 'Какая V2 у глагола <b>take</b>?', options: ['taked', 'took', 'taken', 'taking'], correct: 1, hint: 'take → took → taken' },
    { category: 'irregular', q: 'Какая V3 у глагола <b>take</b>?', options: ['taked', 'took', 'taken', 'taking'], correct: 2, hint: 'take → took → taken' },
    { category: 'irregular', q: 'Какая V2 у глагола <b>write</b>?', options: ['writed', 'wrote', 'written', 'writing'], correct: 1, hint: 'write → wrote → written' },
    { category: 'irregular', q: 'Какая V3 у глагола <b>write</b>?', options: ['writed', 'wrote', 'written', 'writing'], correct: 2, hint: 'write → wrote → written' },
    { category: 'irregular', q: 'Какая V2 у глагола <b>speak</b>?', options: ['speaked', 'spoke', 'spoken', 'speaking'], correct: 1, hint: 'speak → spoke → spoken' },
    { category: 'irregular', q: 'Какая V3 у глагола <b>speak</b>?', options: ['speaked', 'spoke', 'spoken', 'speaking'], correct: 2, hint: 'speak → spoke → spoken' },
    { category: 'irregular', q: 'Какая V2 у глагола <b>break</b>?', options: ['breaked', 'broke', 'broken', 'breaking'], correct: 1, hint: 'break → broke → broken' },
    { category: 'irregular', q: 'Какая V3 у глагола <b>break</b>?', options: ['breaked', 'broke', 'broken', 'breaking'], correct: 2, hint: 'break → broke → broken' },
    { category: 'irregular', q: 'Какая V2 у глагола <b>give</b>?', options: ['gived', 'gave', 'given', 'giving'], correct: 1, hint: 'give → gave → given' },
    { category: 'irregular', q: 'Какая V3 у глагола <b>give</b>?', options: ['gived', 'gave', 'given', 'giving'], correct: 2, hint: 'give → gave → given' },
    { category: 'irregular', q: 'Какая V2 у глагола <b>know</b>?', options: ['knowed', 'knew', 'known', 'knowing'], correct: 1, hint: 'know → knew → known' },
    { category: 'irregular', q: 'Какая V3 у глагола <b>know</b>?', options: ['knowed', 'knew', 'known', 'knowing'], correct: 2, hint: 'know → knew → known' },
    { category: 'irregular', q: 'Какая V2 у глагола <b>come</b>?', options: ['comed', 'came', 'come', 'coming'], correct: 1, hint: 'come → came → come' },
    { category: 'irregular', q: 'Какая V3 у глагола <b>come</b>?', options: ['comed', 'came', 'come', 'coming'], correct: 2, hint: 'come → came → come' },
    { category: 'irregular', q: 'Какая V2 у глагола <b>think</b>?', options: ['thinked', 'thought', 'thinked', 'thinking'], correct: 1, hint: 'think → thought → thought' },
    { category: 'irregular', q: 'Какая V2 у глагола <b>buy</b>?', options: ['buyed', 'bought', 'boughten', 'buying'], correct: 1, hint: 'buy → bought → bought' },
    { category: 'irregular', q: 'Какая V2 у глагола <b>bring</b>?', options: ['bringed', 'brought', 'brang', 'bringing'], correct: 1, hint: 'bring → brought → brought' },
    { category: 'irregular', q: 'Какая V2 у глагола <b>catch</b>?', options: ['catched', 'caught', 'catcht', 'catching'], correct: 1, hint: 'catch → caught → caught' },
    { category: 'irregular', q: 'Какая V2 у глагола <b>teach</b>?', options: ['teached', 'taught', 'teachd', 'teaching'], correct: 1, hint: 'teach → taught → taught' },
    { category: 'irregular', q: 'Какая V2 у глагола <b>feel</b>?', options: ['feeled', 'felt', 'fell', 'feeling'], correct: 1, hint: 'feel → felt → felt' },
    { category: 'irregular', q: 'Какая V2 у глагола <b>leave</b>?', options: ['leaved', 'left', 'loved', 'leaving'], correct: 1, hint: 'leave → left → left' },
    { category: 'irregular', q: 'Какая V2 у глагола <b>meet</b>?', options: ['meeted', 'met', 'mate', 'meeting'], correct: 1, hint: 'meet → met → met' },
    { category: 'irregular', q: 'Какая V2 у глагола <b>sleep</b>?', options: ['sleeped', 'slept', 'slap', 'sleeping'], correct: 1, hint: 'sleep → slept → slept' },
    { category: 'irregular', q: 'Какая V2 у глагола <b>run</b>?', options: ['runned', 'ran', 'run', 'running'], correct: 1, hint: 'run → ran → run' },

    // ═══════ ГЛАГОЛЫ GET / HAVE / TAKE / MAKE / DO / GO / PUT — 25 вопросов ═══════
    { category: 'magic', q: 'Что значит <b>get up</b>?', options: ['лечь спать', 'встать с постели', 'упасть', 'забраться'], correct: 1, hint: 'I get up at 7 am.' },
    { category: 'magic', q: 'Что значит <b>get over</b>?', options: ['перепрыгнуть', 'преодолеть, пережить', 'надеть', 'сойти'], correct: 1, hint: 'Get over it! — Переживи это!' },
    { category: 'magic', q: 'Что значит <b>get along</b>?', options: ['идти рядом', 'ладить', 'уезжать', 'догонять'], correct: 1, hint: 'We get along well.' },
    { category: 'magic', q: 'Что значит <b>get off</b>?', options: ['выйти из транспорта', 'упасть', 'одеться', 'включить'], correct: 0, hint: 'Get off at the next stop.' },
    { category: 'magic', q: 'Что значит <b>get on</b>?', options: ['сесть в транспорт', 'включить', 'одеться', 'упасть'], correct: 0, hint: 'Get on the bus.' },
    { category: 'magic', q: 'Как сказать «принять душ» по-английски?', options: ['take a shower', 'have a shower', 'Оба варианта', 'make a shower'], correct: 2, hint: 'have a shower = take a shower' },
    { category: 'magic', q: 'Что значит <b>have to</b>?', options: ['иметь что-то', 'должен', 'хотеть', 'мочь'], correct: 1, hint: 'I have to go.' },
    { category: 'magic', q: 'Что значит <b>take off</b>?', options: ['приземлиться', 'снять / взлететь', 'взять вверх', 'уехать'], correct: 1, hint: 'Take off your shoes.' },
    { category: 'magic', q: 'Что значит <b>take care</b>?', options: ['взять карту', 'заботиться', 'быть осторожным', 'смотреть'], correct: 1, hint: 'Take care of yourself.' },
    { category: 'magic', q: 'Что значит <b>make up</b>?', options: ['приготовить', 'придумать / помириться', 'наложить макияж', 'составить'], correct: 1, hint: 'She made up a story.' },
    { category: 'magic', q: 'Что значит <b>make sure</b>?', options: ['сделать уверенно', 'убедиться', 'застраховать', 'проверить'], correct: 1, hint: 'Make sure you come.' },
    { category: 'magic', q: 'Что значит <b>do me a favour</b>?', options: ['сделай мне одолжение', 'полюби меня', 'сделай подарок', 'подари мне'], correct: 0, hint: 'Do me a favour, please.' },
    { category: 'magic', q: 'Что значит <b>go out</b>?', options: ['погаснуть', 'выйти / гулять', 'уехать', 'выйти из дома'], correct: 1, hint: 'Let\'s go out.' },
    { category: 'magic', q: 'Что значит <b>go on</b>?', options: ['продолжать', 'уходить', 'включать', 'наступать'], correct: 0, hint: 'Go on, please.' },
    { category: 'magic', q: 'Что значит <b>go back</b>?', options: ['возвращаться', 'отойти', 'пойти назад', 'отступать'], correct: 0, hint: 'I must go back.' },
    { category: 'magic', q: 'Что значит <b>put on</b>?', options: ['поставить на', 'надеть', 'отложить', 'положить'], correct: 1, hint: 'Put on your coat.' },
    { category: 'magic', q: 'Что значит <b>put off</b>?', options: ['выключить', 'отложить', 'снять', 'погасить'], correct: 1, hint: 'Put off the meeting.' },
    { category: 'magic', q: 'Что значит <b>put up with</b>?', options: ['поднять', 'мириться с', 'построить', 'поставить'], correct: 1, hint: 'I can\'t put up with it.' },
    { category: 'magic', q: 'Разница: <b>do</b> vs <b>make</b>?', options: ['Одно и то же', 'do — действие, make — создание', 'make формальнее', 'do только в вопросах'], correct: 1, hint: 'do homework / make coffee' },
    { category: 'magic', q: 'Как правильно: <b>___ a decision</b>?', options: ['do', 'make', 'take', 'have'], correct: 1, hint: 'make a decision' },
    { category: 'magic', q: 'Как правильно: <b>___ homework</b>?', options: ['do', 'make', 'take', 'have'], correct: 0, hint: 'do homework' },
    { category: 'magic', q: 'Как правильно: <b>___ a photo</b>?', options: ['do', 'make', 'take', 'have'], correct: 2, hint: 'take a photo' },
    { category: 'magic', q: 'Как правильно: <b>___ a shower</b>?', options: ['do', 'make', 'take / have', 'go'], correct: 2, hint: 'take a shower = have a shower' },
    { category: 'magic', q: 'Что значит <b>get it</b>?', options: ['получить это', 'понять это', 'взять это', 'найти это'], correct: 1, hint: 'I don\'t get it.' },
    { category: 'magic', q: 'Что значит <b>get dark</b>?', options: ['получить темноту', 'темнеть', 'стать тёмным', 'испачкаться'], correct: 1, hint: 'It gets dark at 6.' },

    // ═══════ ПРЕДЛОГИ — 25 вопросов ═══════
    { category: 'preps', q: 'I go ___ school.', options: ['in', 'to', 'at', 'on'], correct: 1, hint: 'to = направление К цели' },
    { category: 'preps', q: 'She is ___ the room.', options: ['in', 'to', 'on', 'at'], correct: 0, hint: 'in = внутри' },
    { category: 'preps', q: 'The book is ___ the table.', options: ['in', 'at', 'on', 'to'], correct: 2, hint: 'on = на поверхности' },
    { category: 'preps', q: 'Wait ___ the bus stop.', options: ['in', 'on', 'at', 'to'], correct: 2, hint: 'at = точное место' },
    { category: 'preps', q: 'This gift is ___ you.', options: ['to', 'for', 'at', 'with'], correct: 1, hint: 'for = для' },
    { category: 'preps', q: 'I go ___ my friend.', options: ['for', 'at', 'with', 'to'], correct: 2, hint: 'with = вместе с' },
    { category: 'preps', q: 'I can\'t live ___ you.', options: ['with', 'without', 'for', 'at'], correct: 1, hint: 'without = без' },
    { category: 'preps', q: 'Sit ___ me.', options: ['in', 'at', 'by', 'to'], correct: 2, hint: 'by = рядом' },
    { category: 'preps', q: 'I go to work ___ bus.', options: ['in', 'on', 'by', 'at'], correct: 2, hint: 'by = способ передвижения' },
    { category: 'preps', q: 'Get ___ the car.', options: ['in', 'on', 'at', 'to'], correct: 0, hint: 'in — в машину (внутрь)' },
    { category: 'preps', q: 'Get ___ the bus.', options: ['in', 'on', 'at', 'to'], correct: 1, hint: 'on — в автобус (поверхность)' },
    { category: 'preps', q: 'I am ___ home.', options: ['in', 'at', 'on', 'to'], correct: 1, hint: 'at home = дома (фикс.)' },
    { category: 'preps', q: 'I get up ___ 7 o\'clock.', options: ['in', 'on', 'at', 'to'], correct: 2, hint: 'at — с точным временем' },
    { category: 'preps', q: 'I was born ___ 1990.', options: ['in', 'on', 'at', 'to'], correct: 0, hint: 'in — с годами/месяцами' },
    { category: 'preps', q: 'I was born ___ Monday.', options: ['in', 'on', 'at', 'to'], correct: 1, hint: 'on — с днями недели' },
    { category: 'preps', q: 'Look ___ the picture.', options: ['in', 'at', 'on', 'to'], correct: 1, hint: 'look at = смотреть на' },
    { category: 'preps', q: 'Listen ___ me.', options: ['at', 'in', 'to', 'on'], correct: 2, hint: 'listen to = слушать кого-то' },
    { category: 'preps', q: 'I am good ___ maths.', options: ['in', 'at', 'on', 'for'], correct: 1, hint: 'good at = хорошо разбираться' },
    { category: 'preps', q: 'I am interested ___ art.', options: ['in', 'at', 'on', 'for'], correct: 0, hint: 'interested in = интересуюсь' },
    { category: 'preps', q: 'Thank you ___ your help.', options: ['for', 'at', 'on', 'in'], correct: 0, hint: 'thank for = спасибо за' },
    { category: 'preps', q: 'I am afraid ___ dogs.', options: ['at', 'in', 'of', 'from'], correct: 2, hint: 'afraid of = бояться' },
    { category: 'preps', q: 'Wait ___ me!', options: ['at', 'in', 'on', 'for'], correct: 3, hint: 'wait for = ждать кого-то' },
    { category: 'preps', q: 'I arrived ___ London.', options: ['in', 'at', 'to', 'on'], correct: 0, hint: 'arrive in = приехать в город' },
    { category: 'preps', q: 'Depend ___ me.', options: ['in', 'at', 'on', 'to'], correct: 2, hint: 'depend on = зависеть от' },
    { category: 'preps', q: 'I am proud ___ you.', options: ['at', 'in', 'of', 'for'], correct: 2, hint: 'proud of = гордиться' },

    // ═══════ ПРИСТАВКИ И СУФФИКСЫ — 25 вопросов ═══════
    { category: 'prefixes', q: 'Что значит приставка <b>pre-</b>?', options: ['после', 'до, заранее', 'против', 'через'], correct: 1, hint: 'preview = предпросмотр' },
    { category: 'prefixes', q: 'Что значит приставка <b>post-</b>?', options: ['до', 'после', 'не', 'снова'], correct: 1, hint: 'postwar = послевоенный' },
    { category: 'prefixes', q: 'Что значит приставка <b>re-</b>?', options: ['не', 'снова, обратно', 'вниз', 'через'], correct: 1, hint: 'rewrite = переписать' },
    { category: 'prefixes', q: 'Что значит приставка <b>un-</b>?', options: ['снова', 'не, обратное', 'до', 'под'], correct: 1, hint: 'unhappy = несчастный' },
    { category: 'prefixes', q: 'Что значит приставка <b>dis-</b>?', options: ['не, разделение', 'до', 'сверх', 'вместе'], correct: 0, hint: 'disagree = не соглашаться' },
    { category: 'prefixes', q: 'Что значит приставка <b>de-</b>?', options: ['снова', 'вниз, убрать', 'не', 'между'], correct: 1, hint: 'delete = удалить' },
    { category: 'prefixes', q: 'Что значит приставка <b>mis-</b>?', options: ['правильно', 'неправильно', 'снова', 'сверх'], correct: 1, hint: 'mistake = ошибка' },
    { category: 'prefixes', q: 'Что значит приставка <b>over-</b>?', options: ['под', 'сверх, слишком', 'через', 'не'], correct: 1, hint: 'oversleep = проспать' },
    { category: 'prefixes', q: 'Что значит приставка <b>under-</b>?', options: ['над', 'под, недостаточно', 'через', 'снова'], correct: 1, hint: 'underground = подземный' },
    { category: 'prefixes', q: 'Что значит приставка <b>out-</b>?', options: ['внутрь', 'наружу, превзойти', 'до', 'не'], correct: 1, hint: 'outrun = обогнать' },
    { category: 'prefixes', q: 'Что делает суффикс <b>-ed</b>?', options: ['настоящее', 'прошедшее / сделанный', 'будущее', 'снова'], correct: 1, hint: 'worked = работал' },
    { category: 'prefixes', q: 'Что делает суффикс <b>-ing</b>?', options: ['прошедшее', 'действие / процесс', 'множественное', 'отрицание'], correct: 1, hint: 'running = бег / бегущий' },
    { category: 'prefixes', q: 'Что делает суффикс <b>-er / -or</b>?', options: ['прилагательное', 'тот, кто делает', 'прошедшее', 'наречие'], correct: 1, hint: 'teacher = учитель' },
    { category: 'prefixes', q: 'Что делает суффикс <b>-ly</b>?', options: ['существительное', 'наречие (как?)', 'прилагательное', 'глагол'], correct: 1, hint: 'quickly = быстро' },
    { category: 'prefixes', q: 'Что значит суффикс <b>-ful</b>?', options: ['без чего-то', 'полный чего-то', 'тот, кто', 'процесс'], correct: 1, hint: 'helpful = полезный' },
    { category: 'prefixes', q: 'Что значит суффикс <b>-less</b>?', options: ['полный', 'без чего-то', 'тот, кто', 'сделанный'], correct: 1, hint: 'hopeless = безнадёжный' },
    { category: 'prefixes', q: 'Что значит суффикс <b>-ness</b>?', options: ['состояние / качество', 'без', 'тот, кто', 'процесс'], correct: 0, hint: 'happiness = счастье' },
    { category: 'prefixes', q: 'Как переводится <b>unhappy</b>?', options: ['счастливый', 'несчастный', 'пересчастливый', 'почти счастливый'], correct: 1, hint: 'un- + happy' },
    { category: 'prefixes', q: 'Как переводится <b>rewrite</b>?', options: ['писать', 'переписать', 'не писать', 'дописать'], correct: 1, hint: 're- + write' },
    { category: 'prefixes', q: 'Как переводится <b>dislike</b>?', options: ['нравиться', 'не любить', 'любить сильно', 'перелюбить'], correct: 1, hint: 'dis- + like' },
    { category: 'prefixes', q: 'Как переводится <b>oversleep</b>?', options: ['поспать', 'проспать', 'недоспать', 'выспаться'], correct: 1, hint: 'over- + sleep' },
    { category: 'prefixes', q: 'Как переводится <b>teacher</b>?', options: ['тот, кого учат', 'тот, кто учит', 'учёба', 'ученик'], correct: 1, hint: 'teach + -er' },
    { category: 'prefixes', q: 'Как переводится <b>quickly</b>?', options: ['быстрый', 'быстро', 'быстрота', 'убыстрение'], correct: 1, hint: 'quick + -ly' },
    { category: 'prefixes', q: 'Как переводится <b>homeless</b>?', options: ['домашний', 'бездомный', 'дом', 'дома'], correct: 1, hint: 'home + -less' },
    { category: 'prefixes', q: 'Как переводится <b>careful</b>?', options: ['беззаботный', 'осторожный', 'забота', 'небрежный'], correct: 1, hint: 'care + -ful' },

    // ═══════ КОРНИ-КОНСТРУКТОРЫ — 25 вопросов ═══════
    { category: 'roots', q: 'Что значит корень <b>port</b>?', options: ['смотреть', 'нести', 'бросать', 'говорить'], correct: 1, hint: 'port = носить (export, import)' },
    { category: 'roots', q: 'Что значит корень <b>ject</b>?', options: ['бросать', 'нести', 'видеть', 'писать'], correct: 0, hint: 'ject = бросать (reject, inject)' },
    { category: 'roots', q: 'Что значит корень <b>spect</b>?', options: ['говорить', 'смотреть', 'строить', 'двигать'], correct: 1, hint: 'spect = смотреть (inspect, respect)' },
    { category: 'roots', q: 'Что значит корень <b>dict</b>?', options: ['писать', 'говорить', 'смотреть', 'тянуть'], correct: 1, hint: 'dict = говорить (predict, dictate)' },
    { category: 'roots', q: 'Что значит корень <b>scrib / script</b>?', options: ['писать', 'читать', 'смотреть', 'слушать'], correct: 0, hint: 'scrib = писать (describe, subscribe)' },
    { category: 'roots', q: 'Что значит корень <b>struct</b>?', options: ['ломать', 'строить', 'нести', 'двигать'], correct: 1, hint: 'struct = строить (construct)' },
    { category: 'roots', q: 'Что значит корень <b>tract</b>?', options: ['толкать', 'тянуть', 'бросать', 'нести'], correct: 1, hint: 'tract = тянуть (attract, extract)' },
    { category: 'roots', q: 'Что значит корень <b>form</b>?', options: ['форма', 'звук', 'свет', 'движение'], correct: 0, hint: 'form = форма (reform, transform)' },
    { category: 'roots', q: 'Что значит корень <b>vis / vid</b>?', options: ['видеть', 'слышать', 'говорить', 'писать'], correct: 0, hint: 'vis = видеть (visible, revise)' },
    { category: 'roots', q: 'Что значит корень <b>cred</b>?', options: ['верить', 'видеть', 'делать', 'носить'], correct: 0, hint: 'cred = верить (credit, incredible)' },
    { category: 'roots', q: 'Что значит корень <b>mem</b>?', options: ['двигать', 'память', 'нести', 'строить'], correct: 1, hint: 'mem = память (memory, remember)' },
    { category: 'roots', q: 'Что значит корень <b>sens / sent</b>?', options: ['видеть', 'чувствовать', 'говорить', 'писать'], correct: 1, hint: 'sens = чувство (sense, sentiment)' },
    { category: 'roots', q: 'Что значит корень <b>viv / vit</b>?', options: ['жить', 'умирать', 'двигаться', 'думать'], correct: 0, hint: 'viv = жить (survive, revive)' },
    { category: 'roots', q: 'Что значит корень <b>mort</b>?', options: ['жизнь', 'смерть', 'болезнь', 'здоровье'], correct: 1, hint: 'mort = смерть (mortal, immortal)' },
    { category: 'roots', q: 'Что значит корень <b>terr</b>?', options: ['вода', 'земля', 'огонь', 'воздух'], correct: 1, hint: 'terr = земля (territory, terrace)' },
    { category: 'roots', q: 'Что значит корень <b>phon</b>?', options: ['свет', 'звук', 'цвет', 'форма'], correct: 1, hint: 'phon = звук (telephone, microphone)' },
    { category: 'roots', q: 'Что значит корень <b>bio</b>?', options: ['жизнь', 'смерть', 'земля', 'вода'], correct: 0, hint: 'bio = жизнь (biology, biography)' },
    { category: 'roots', q: 'Что значит корень <b>tele</b>?', options: ['рядом', 'далеко', 'быстро', 'медленно'], correct: 1, hint: 'tele = далеко (telephone, telescope)' },
    { category: 'roots', q: 'Что значит корень <b>graph</b>?', options: ['звук', 'писать', 'видеть', 'считать'], correct: 1, hint: 'graph = писать (photograph, paragraph)' },
    { category: 'roots', q: 'Как переводится <b>export</b>?', options: ['импорт', 'экспорт', 'транспорт', 'рапорт'], correct: 1, hint: 'ex- (наружу) + port (нести)' },
    { category: 'roots', q: 'Как переводится <b>predict</b>?', options: ['противоречить', 'предсказать', 'диктовать', 'сказать'], correct: 1, hint: 'pre- (заранее) + dict (говорить)' },
    { category: 'roots', q: 'Как переводится <b>inspect</b>?', options: ['уважать', 'осматривать', 'подозревать', 'перспектива'], correct: 1, hint: 'in- (внутрь) + spect (смотреть)' },
    { category: 'roots', q: 'Как переводится <b>reduce</b>?', options: ['производить', 'уменьшить', 'проводить', 'вводить'], correct: 1, hint: 're- (назад) + duct (вести)' },
    { category: 'roots', q: 'Как переводится <b>survive</b>?', options: ['ожить', 'выжить', 'родиться', 'умереть'], correct: 1, hint: 'sur- (сверх) + viv (жить)' },
    { category: 'roots', q: 'Как переводится <b>incredible</b>?', options: ['кредитный', 'невероятный', 'верующий', 'правдивый'], correct: 1, hint: 'in- (не) + cred (верить) + -ible' },

    // ═══════ ФРАЗЫ И УНИВЕРСАЛЬНЫЕ СЛОВА — 20 вопросов ═══════
    { category: 'phrases', q: 'Как сказать «Как дела?» по-английски?', options: ['How do you do?', 'How are you?', 'What are you?', 'Who are you?'], correct: 1, hint: 'How are you?' },
    { category: 'phrases', q: 'Что значит <b>How do you do?</b>', options: ['Как поживаешь?', 'Приятно познакомиться (формально)', 'Что ты делаешь?', 'Как ты это делаешь?'], correct: 1, hint: 'Очень формальное приветствие при знакомстве' },
    { category: 'phrases', q: 'Что значит <b>Never mind</b>?', options: ['Никогда не думай', 'Неважно, забудь', 'Никогда не забывай', 'Не думай об этом'], correct: 1, hint: 'Never mind = Ничего страшного' },
    { category: 'phrases', q: 'Что значит <b>By the way</b>?', options: ['По дороге', 'Кстати', 'В любом случае', 'Мимо'], correct: 1, hint: 'By the way = Кстати' },
    { category: 'phrases', q: 'Что значит <b>Take your time</b>?', options: ['Возьми время', 'Не спеши', 'Засеки время', 'Ускорься'], correct: 1, hint: 'Take your time = Не торопись' },
    { category: 'phrases', q: 'Что значит <b>It doesn\'t matter</b>?', options: ['Это не важно', 'Это не материал', 'Это не работает', 'Это не считается'], correct: 0, hint: 'It doesn\'t matter = Неважно' },
    { category: 'phrases', q: 'Что значит <b>I have no idea</b>?', options: ['У меня нет идей', 'Понятия не имею', 'Я не думаю', 'У меня нет времени'], correct: 1, hint: 'I have no idea = Понятия не имею' },
    { category: 'phrases', q: 'Что значит <b>Long time no see</b>?', options: ['Долго не виделись', 'Долго не смотрел', 'Давно не видел', 'Длинное время'], correct: 0, hint: 'Long time no see = Давно не виделись' },
    { category: 'phrases', q: 'Что значит <b>What\'s up?</b>', options: ['Что сверху?', 'Как дела? (неформально)', 'Что случилось?', 'Что вверх?'], correct: 1, hint: 'What\'s up = Как дела? (разг.)' },
    { category: 'phrases', q: 'Что значит <b>I\'m starving</b>?', options: ['Я умираю от голода', 'Я устал', 'Я не хочу есть', 'Я сыт'], correct: 0, hint: 'I\'m starving = Умираю с голода' },
    { category: 'phrases', q: 'Что значит <b>Piece of cake</b>?', options: ['Кусок торта', 'Проще простого', 'Очень вкусно', 'День рождения'], correct: 1, hint: 'Piece of cake = Плёвое дело' },
    { category: 'phrases', q: 'Что значит <b>Break a leg!</b>', options: ['Сломай ногу!', 'Удачи! (театр.)', 'Не упади!', 'Осторожно!'], correct: 1, hint: 'Break a leg = Ни пуха ни пера!' },
    { category: 'phrases', q: 'Что значит <b>Hit the books</b>?', options: ['Ударить книги', 'Заняться учёбой', 'Купить книги', 'Читать лёжа'], correct: 1, hint: 'Hit the books = Засесть за учёбу' },
    { category: 'phrases', q: 'Что значит <b>Under the weather</b>?', options: ['Под дождём', 'Нездоровится', 'На улице', 'В отпуске'], correct: 1, hint: 'Under the weather = Неважно себя чувствовать' },
    { category: 'phrases', q: 'Какое слово-заглушка значит «вещь, штука»?', options: ['thing', 'way', 'time', 'guy'], correct: 0, hint: 'thing = штука, вещь' },
    { category: 'phrases', q: 'Какое слово-заглушка значит «вещи, барахло»?', options: ['stuff', 'thing', 'place', 'way'], correct: 0, hint: 'stuff = вещи (разг.)' },
    { category: 'phrases', q: 'Какое слово-заглушка значит «способ, путь»?', options: ['thing', 'way', 'place', 'time'], correct: 1, hint: 'way = способ, путь' },
    { category: 'phrases', q: 'Как правильно: <b>by the ___</b> (= кстати)?', options: ['road', 'way', 'street', 'path'], correct: 1, hint: 'by the way = кстати' },
    { category: 'phrases', q: 'Что сказать, если не расслышал?', options: ['What?', 'Pardon? / Sorry?', 'Repeat!', 'Speak!'], correct: 1, hint: 'Pardon? = Простите? (вежливо)' },
    { category: 'phrases', q: 'Как попросить говорить медленнее?', options: ['Speak slow!', 'Speak slowly, please.', 'Slow speech!', 'More slow!'], correct: 1, hint: 'Speak slowly, please' }
];

// ===== ВСПОМОГАТЕЛЬНОЕ: перемешать массив =====
function shuffleArray(arr) {
    const a = [...arr];
    for (let i = a.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [a[i], a[j]] = [a[j], a[i]];
    }
    return a;
}
