// quizgen.js v11 — готовые предложения + все типы вопросов
// Каждое слово имеет свой список проверенных предложений.

// ═══════════════════════════════════════════════
// ГОТОВЫЕ ПРЕДЛОЖЕНИЯ (проверенные вручную)
// ═══════════════════════════════════════════════
const SENTENCES = {
    // ═══ A ═══
    'able': [['He is able to swim.', 'Он умеет плавать.']],
    'about': [['Tell me about it.', 'Расскажи мне об этом.']],
    'above': [['The sky is above us.', 'Небо над нами.']],
    'abroad': [['She lives abroad.', 'Она живёт за границей.']],
    'accept': [['I accept your offer.', 'Я принимаю твоё предложение.']],
    'accident': [['There was an accident.', 'Была авария.']],
    'account': [['I have a bank account.', 'У меня есть банковский счёт.']],
    'achieve': [['You can achieve your goal.', 'Ты можешь достичь цели.']],
    'across': [['Walk across the street.', 'Перейди через улицу.']],
    'act': [['Act now!', 'Действуй сейчас!']],
    'action': [['Actions speak louder than words.', 'Действия громче слов.']],
    'active': [['She is very active.', 'Она очень активная.']],
    'activity': [['What is your favourite activity?', 'Какое твоё любимое занятие?']],
    'actor': [['He is a famous actor.', 'Он известный актёр.']],
    'actually': [['Actually, I do not know.', 'На самом деле, я не знаю.']],
    'add': [['Add some salt.', 'Добавь немного соли.']],
    'address': [['What is your address?', 'Какой у тебя адрес?']],
    'admit': [['I admit my mistake.', 'Я признаю свою ошибку.']],
    'adult': [['Adults only.', 'Только для взрослых.']],
    'advice': [['Give me some advice.', 'Дай мне совет.']],
    'advise': [['I advise you to rest.', 'Советую тебе отдохнуть.']],
    'afraid': [['I am afraid of dogs.', 'Я боюсь собак.']],
    'after': [['After dinner we walked.', 'После ужина мы гуляли.']],
    'afternoon': [['Good afternoon!', 'Добрый день!']],
    'again': [['Say it again.', 'Скажи это снова.']],
    'against': [['I am against it.', 'Я против этого.']],
    'age': [['What is your age?', 'Сколько тебе лет?']],
    'ago': [['Two years ago.', 'Два года назад.']],
    'agree': [['I agree with you.', 'Я согласен с тобой.']],
    'ahead': [['Go ahead!', 'Иди вперёд!']],
    'air': [['Fresh air is good.', 'Свежий воздух полезен.']],
    'airport': [['I go to the airport.', 'Я иду в аэропорт.']],
    'alive': [['He is still alive.', 'Он ещё жив.']],
    'all': [['That is all.', 'Это всё.']],
    'allow': [['Allow me to help.', 'Позволь мне помочь.']],
    'almost': [['I am almost ready.', 'Я почти готов.']],
    'alone': [['I live alone.', 'Я живу один.']],
    'along': [['Walk along the river.', 'Иди вдоль реки.']],
    'already': [['I am already here.', 'Я уже здесь.']],
    'also': [['Me also.', 'Я тоже.']],
    'although': [['Although it is raining, I go out.', 'Хотя идёт дождь, я выхожу.']],
    'always': [['I always help.', 'Я всегда помогаю.']],
    'amazing': [['What an amazing day!', 'Какой удивительный день!']],
    'among': [['Among friends.', 'Среди друзей.']],
    'amount': [['A large amount of money.', 'Большое количество денег.']],
    'and': [['You and I.', 'Ты и я.']],
    'angry': [['Do not be angry.', 'Не злись.']],
    'animal': [['I love animals.', 'Я люблю животных.']],
    'another': [['Give me another one.', 'Дай мне другой.']],
    'answer': [['Your answer is correct.', 'Твой ответ правильный.']],
    'any': [['Any questions?', 'Есть вопросы?']],
    'anybody': [['Is anybody home?', 'Кто-нибудь дома?']],
    'anything': [['I can do anything.', 'Я могу всё.']],
    'anyway': [['Anyway, let us go.', 'В любом случае, пойдём.']],
    'anywhere': [['I cannot find it anywhere.', 'Я нигде не могу это найти.']],
    'apartment': [['A nice apartment.', 'Хорошая квартира.']],
    'apologize': [['I apologize.', 'Я извиняюсь.']],
    'appear': [['The sun appeared.', 'Появилось солнце.']],
    'apple': [['An apple a day.', 'Яблоко в день.']],
    'apply': [['Apply the rules.', 'Применяй правила.']],
    'appointment': [['I have an appointment.', 'У меня назначена встреча.']],
    'area': [['This is a quiet area.', 'Это тихая зона.']],
    'argue': [['Do not argue with me.', 'Не спорь со мной.']],
    'arm': [['My arm hurts.', 'У меня болит рука.']],
    'army': [['He is in the army.', 'Он служит в армии.']],
    'around': [['Look around.', 'Осмотрись.']],
    'arrange': [['Arrange a meeting.', 'Организуй встречу.']],
    'arrive': [['We arrived at five.', 'Мы прибыли в пять.']],
    'art': [['I love art.', 'Я люблю искусство.']],
    'article': [['Read this article.', 'Прочитай эту статью.']],
    'artist': [['She is an artist.', 'Она художница.']],
    'as': [['As you wish.', 'Как хочешь.']],
    'ask': [['Ask me a question.', 'Задай мне вопрос.']],
    'asleep': [['The baby is asleep.', 'Ребёнок спит.']],
    'at': [['At home.', 'Дома.']],
    'attack': [['The dog attacked.', 'Собака напала.']],
    'attention': [['Pay attention!', 'Обрати внимание!']],
    'attitude': [['Your attitude matters.', 'Твоё отношение важно.']],
    'attract': [['Attract attention.', 'Привлекать внимание.']],
    'audience': [['The audience clapped.', 'Аудитория аплодировала.']],
    'author': [['Who is the author?', 'Кто автор?']],
    'autumn': [['I love autumn.', 'Я люблю осень.']],
    'available': [['Is it available?', 'Это доступно?']],
    'average': [['The average cost.', 'Средняя стоимость.']],
    'avoid': [['Avoid the traffic.', 'Избегай пробок.']],
    'away': [['Go away!', 'Уходи!']],
    'awful': [['Awful weather.', 'Ужасная погода.']],

    // ═══ B ═══
    'baby': [['The baby is crying.', 'Ребёнок плачет.']],
    'back': [['My back hurts.', 'У меня болит спина.']],
    'bad': [['That is too bad.', 'Как жаль.']],
    'bag': [['Where is my bag?', 'Где моя сумка?']],
    'ball': [['Throw the ball.', 'Брось мяч.']],
    'bank': [['Go to the bank.', 'Иди в банк.']],
    'base': [['Military base.', 'Военная база.']],
    'basic': [['Basic knowledge.', 'Базовые знания.']],
    'basket': [['A basket of fruit.', 'Корзина фруктов.']],
    'bath': [['Take a bath.', 'Прими ванну.']],
    'bathroom': [['Where is the bathroom?', 'Где ванная?']],
    'be': [['To be or not to be.', 'Быть или не быть.']],
    'beach': [['Let us go to the beach.', 'Пойдём на пляж.']],
    'bear': [['A big brown bear.', 'Большой бурый медведь.']],
    'beat': [['Beat the eggs.', 'Взбей яйца.']],
    'beautiful': [['A beautiful day.', 'Красивый день.']],
    'because': [['Because I said so.', 'Потому что я так сказал.']],
    'become': [['He became a doctor.', 'Он стал врачом.']],
    'bed': [['Go to bed.', 'Иди спать.']],
    'bedroom': [['My bedroom is small.', 'Моя спальня маленькая.']],
    'before': [['Before you go, call me.', 'Прежде чем уйти, позвони мне.']],
    'begin': [['Let us begin.', 'Давай начнём.']],
    'behind': [['Behind the house.', 'За домом.']],
    'believe': [['I believe you.', 'Я тебе верю.']],
    'bell': [['The bell rang.', 'Прозвенел звонок.']],
    'belong': [['It belongs to me.', 'Это принадлежит мне.']],
    'below': [['Below zero.', 'Ниже нуля.']],
    'belt': [['Fasten your belt.', 'Пристегни ремень.']],
    'bench': [['Sit on the bench.', 'Сядь на скамейку.']],
    'best': [['The best day.', 'Лучший день.']],
    'better': [['Much better.', 'Намного лучше.']],
    'between': [['Between us.', 'Между нами.']],
    'bicycle': [['Ride a bicycle.', 'Кати на велосипеде.']],
    'big': [['A big house.', 'Большой дом.']],
    'bike': [['My bike is red.', 'Мой велосипед красный.']],
    'bill': [['Pay the bill.', 'Оплати счёт.']],
    'bird': [['A little bird.', 'Маленькая птица.']],
    'birthday': [['Happy birthday!', 'С днём рождения!']],
    'bit': [['A bit of sugar.', 'Кусочек сахара.']],
    'bite': [['Do not bite me.', 'Не кусай меня.']],
    'black': [['A black cat.', 'Чёрная кошка.']],
    'blood': [['Blood test.', 'Анализ крови.']],
    'blow': [['Blow out the candle.', 'Задуй свечу.']],
    'blue': [['A blue sky.', 'Синее небо.']],
    'board': [['A wooden board.', 'Деревянная доска.']],
    'boat': [['A small boat.', 'Маленькая лодка.']],
    'body': [['Take care of your body.', 'Заботься о своём теле.']],
    'bone': [['A broken bone.', 'Сломанная кость.']],
    'book': [['Read a book.', 'Прочитай книгу.']],
    'boot': [['A pair of boots.', 'Пара ботинок.']],
    'border': [['Cross the border.', 'Пересеки границу.']],
    'boring': [['The film is boring.', 'Фильм скучный.']],
    'born': [['I was born in 1990.', 'Я родился в 1990.']],
    'borrow': [['Can I borrow a pen?', 'Можно одолжить ручку?']],
    'boss': [['My boss is strict.', 'Мой начальник строгий.']],
    'both': [['Both of us.', 'Мы оба.']],
    'bottle': [['A bottle of water.', 'Бутылка воды.']],
    'bottom': [['The bottom of the sea.', 'Дно моря.']],
    'bowl': [['A bowl of soup.', 'Тарелка супа.']],
    'box': [['A cardboard box.', 'Картонная коробка.']],
    'boy': [['A little boy.', 'Маленький мальчик.']],
    'brain': [['Use your brain.', 'Используй мозг.']],
    'brave': [['A brave soldier.', 'Смелый солдат.']],
    'bread': [['Buy some bread.', 'Купи хлеба.']],
    'break': [['Do not break it.', 'Не сломай это.']],
    'breakfast': [['Have breakfast.', 'Позавтракай.']],
    'breathe': [['Breathe slowly.', 'Дыши медленно.']],
    'bridge': [['Cross the bridge.', 'Перейди мост.']],
    'bright': [['A bright light.', 'Яркий свет.']],
    'bring': [['Bring me water.', 'Принеси мне воды.']],
    'broad': [['A broad street.', 'Широкая улица.']],
    'brother': [['My little brother.', 'Мой младший брат.']],
    'brown': [['Brown eyes.', 'Карие глаза.']],
    'brush': [['A toothbrush.', 'Зубная щётка.']],
    'build': [['Build a house.', 'Построй дом.']],
    'building': [['A tall building.', 'Высокое здание.']],
    'burn': [['Do not burn yourself.', 'Не обожгись.']],
    'bus': [['Take the bus.', 'Сядь на автобус.']],
    'business': [['Do business.', 'Занимайся бизнесом.']],
    'busy': [['I am busy.', 'Я занят.']],
    'but': [['But I like it.', 'Но мне это нравится.']],
    'butter': [['Bread and butter.', 'Хлеб с маслом.']],
    'button': [['Press the button.', 'Нажми кнопку.']],
    'buy': [['Buy some milk.', 'Купи молока.']],
    'by': [['By the way.', 'Кстати.']],
    'bye': [['Bye for now!', 'Пока!']],

    // ═══ C ═══
    'cake': [['A birthday cake.', 'Праздничный торт.']],
    'call': [['Call me later.', 'Позвони мне позже.']],
    'calm': [['Stay calm.', 'Оставайся спокойным.']],
    'camera': [['A new camera.', 'Новая камера.']],
    'camp': [['A summer camp.', 'Летний лагерь.']],
    'can': [['I can swim.', 'Я умею плавать.']],
    'candle': [['Light a candle.', 'Зажги свечу.']],
    'cap': [['A red cap.', 'Красная кепка.']],
    'capital': [['The capital of Russia.', 'Столица России.']],
    'car': [['My car is red.', 'Моя машина красная.']],
    'card': [['A birthday card.', 'Открытка с днём рождения.']],
    'care': [['Take care!', 'Береги себя!']],
    'careful': [['Be careful!', 'Будь осторожен!']],
    'carrot': [['A fresh carrot.', 'Свежая морковь.']],
    'carry': [['Carry this bag.', 'Неси эту сумку.']],
    'case': [['In any case.', 'В любом случае.']],
    'cash': [['Pay in cash.', 'Оплати наличными.']],
    'castle': [['An old castle.', 'Старый замок.']],
    'cat': [['The cat is sleeping.', 'Кошка спит.']],
    'catch': [['Catch the ball!', 'Лови мяч!']],
    'cause': [['The cause of the problem.', 'Причина проблемы.']],
    'ceiling': [['Look at the ceiling.', 'Посмотри на потолок.']],
    'celebrate': [['Let us celebrate!', 'Давай отпразднуем!']],
    'centre': [['The city centre.', 'Центр города.']],
    'century': [['The twenty-first century.', 'Двадцать первый век.']],
    'certain': [['I am certain.', 'Я уверен.']],
    'certainly': [['Certainly, you can.', 'Конечно, ты можешь.']],
    'chair': [['Sit on the chair.', 'Сядь на стул.']],
    'chance': [['Give me a chance.', 'Дай мне шанс.']],
    'change': [['Change your mind.', 'Передумай.']],
    'chapter': [['Read the first chapter.', 'Прочитай первую главу.']],
    'character': [['A strong character.', 'Сильный характер.']],
    'cheap': [['A cheap hotel.', 'Дешёвый отель.']],
    'check': [['Check your email.', 'Проверь свою почту.']],
    'cheese': [['Cheese and bread.', 'Сыр и хлеб.']],
    'chicken': [['Fried chicken.', 'Жареная курица.']],
    'child': [['A small child.', 'Маленький ребёнок.']],
    'chocolate': [['A bar of chocolate.', 'Плитка шоколада.']],
    'choice': [['Your choice.', 'Твой выбор.']],
    'choose': [['Choose a color.', 'Выбери цвет.']],
    'church': [['An old church.', 'Старая церковь.']],
    'cinema': [['Let us go to the cinema.', 'Пойдём в кино.']],
    'circle': [['Draw a circle.', 'Нарисуй круг.']],
    'city': [['A big city.', 'Большой город.']],
    'class': [['My English class.', 'Мой урок английского.']],
    'clean': [['A clean room.', 'Чистая комната.']],
    'clear': [['A clear sky.', 'Ясное небо.']],
    'clever': [['A clever boy.', 'Умный мальчик.']],
    'climb': [['Climb the mountain.', 'Взберись на гору.']],
    'clock': [['Look at the clock.', 'Посмотри на часы.']],
    'close': [['Close the door.', 'Закрой дверь.']],
    'clothes': [['Buy new clothes.', 'Купи новую одежду.']],
    'cloud': [['A white cloud.', 'Белое облако.']],
    'club': [['A sports club.', 'Спортивный клуб.']],
    'coach': [['Our coach is strict.', 'Наш тренер строгий.']],
    'coast': [['The east coast.', 'Восточное побережье.']],
    'coat': [['Put on your coat.', 'Надень пальто.']],
    'coffee': [['A cup of coffee.', 'Чашка кофе.']],
    'coin': [['A gold coin.', 'Золотая монета.']],
    'cold': [['Cold water.', 'Холодная вода.']],
    'collect': [['Collect stamps.', 'Собирай марки.']],
    'college': [['Go to college.', 'Иди в колледж.']],
    'colour': [['What colour is it?', 'Какого это цвета?']],
    'come': [['Come here!', 'Иди сюда!']],
    'comfortable': [['A comfortable bed.', 'Удобная кровать.']],
    'common': [['A common mistake.', 'Частая ошибка.']],
    'company': [['A big company.', 'Большая компания.']],
    'compare': [['Compare these two.', 'Сравни эти два.']],
    'compete': [['We compete together.', 'Мы соревнуемся вместе.']],
    'competition': [['A music competition.', 'Музыкальный конкурс.']],
    'complain': [['Do not complain.', 'Не жалуйся.']],
    'complete': [['Complete the task.', 'Заверши задачу.']],
    'computer': [['I use a computer.', 'Я использую компьютер.']],
    'concert': [['A rock concert.', 'Рок-концерт.']],
    'condition': [['In good condition.', 'В хорошем состоянии.']],
    'connect': [['Connect the cable.', 'Подключи кабель.']],
    'consider': [['Consider this option.', 'Рассмотри этот вариант.']],
    'contact': [['Contact me later.', 'Свяжись со мной позже.']],
    'contain': [['It contains sugar.', 'Он содержит сахар.']],
    'continue': [['Continue reading.', 'Продолжай читать.']],
    'contract': [['Sign the contract.', 'Подпиши контракт.']],
    'control': [['Control your emotions.', 'Контролируй свои эмоции.']],
    'conversation': [['A long conversation.', 'Долгий разговор.']],
    'cook': [['I cook dinner.', 'Я готовлю ужин.']],
    'cool': [['Cool weather.', 'Прохладная погода.']],
    'copy': [['Make a copy.', 'Сделай копию.']],
    'corner': [['At the corner.', 'На углу.']],
    'correct': [['The correct answer.', 'Правильный ответ.']],
    'cost': [['How much does it cost?', 'Сколько это стоит?']],
    'cough': [['A bad cough.', 'Сильный кашель.']],
    'count': [['Count to ten.', 'Считай до десяти.']],
    'country': [['A beautiful country.', 'Красивая страна.']],
    'couple': [['A young couple.', 'Молодая пара.']],
    'course': [['An English course.', 'Курс английского.']],
    'court': [['A tennis court.', 'Теннисный корт.']],
    'cover': [['Cover the food.', 'Накрой еду.']],
    'cow': [['The cow is eating.', 'Корова ест.']],
    'crazy': [['That is crazy!', 'Это безумие!']],
    'cream': [['Ice cream.', 'Мороженое.']],
    'create': [['Create a new project.', 'Создай новый проект.']],
    'credit': [['A credit card.', 'Кредитная карта.']],
    'crime': [['A serious crime.', 'Серьёзное преступление.']],
    'crisis': [['An economic crisis.', 'Экономический кризис.']],
    'cross': [['Cross the road.', 'Перейди дорогу.']],
    'crowd': [['A big crowd.', 'Большая толпа.']],
    'cry': [['Do not cry.', 'Не плачь.']],
    'culture': [['Russian culture.', 'Русская культура.']],
    'cup': [['A cup of tea.', 'Чашка чая.']],
    'customer': [['The customer is always right.', 'Клиент всегда прав.']],
    'cut': [['Cut the paper.', 'Разрежь бумагу.']],

    // ═══ D ═══
    'dad': [['My dad is a driver.', 'Мой папа водитель.']],
    'damage': [['The damage was big.', 'Ущерб был большой.']],
    'dance': [['Let us dance!', 'Давай танцевать!']],
    'danger': [['A great danger.', 'Большая опасность.']],
    'dangerous': [['A dangerous road.', 'Опасная дорога.']],
    'dark': [['A dark night.', 'Тёмная ночь.']],
    'date': [['What is the date today?', 'Какое сегодня число?']],
    'daughter': [['My daughter is a student.', 'Моя дочь студентка.']],
    'day': [['Have a nice day!', 'Хорошего дня!']],
    'dead': [['The tree is dead.', 'Дерево мёртвое.']],
    'deal': [['A good deal.', 'Хорошая сделка.']],
    'dear': [['Dear friend.', 'Дорогой друг.']],
    'death': [['Life and death.', 'Жизнь и смерть.']],
    'debt': [['Pay your debt.', 'Оплати свой долг.']],
    'decide': [['I decide now.', 'Я решаю сейчас.']],
    'decision': [['A difficult decision.', 'Трудное решение.']],
    'deep': [['A deep river.', 'Глубокая река.']],
    'defend': [['Defend your home.', 'Защити свой дом.']],
    'degree': [['A university degree.', 'Университетская степень.']],
    'delay': [['A long delay.', 'Долгая задержка.']],
    'delicious': [['Delicious food!', 'Вкусная еда!']],
    'deliver': [['Deliver the letter.', 'Доставь письмо.']],
    'demand': [['High demand.', 'Большой спрос.']],
    'dentist': [['Go to the dentist.', 'Иди к стоматологу.']],
    'department': [['A big department.', 'Большой отдел.']],
    'depend': [['Do not depend on me.', 'Не завись от меня.']],
    'describe': [['Describe the picture.', 'Опиши картину.']],
    'desert': [['A hot desert.', 'Жаркая пустыня.']],
    'design': [['A modern design.', 'Современный дизайн.']],
    'desk': [['At the desk.', 'За столом.']],
    'destroy': [['Do not destroy it.', 'Не разрушай это.']],
    'detail': [['Every detail matters.', 'Каждая деталь важна.']],
    'develop': [['Develop your skills.', 'Развивай свои навыки.']],
    'diary': [['Write in your diary.', 'Пиши в дневник.']],
    'dictionary': [['An English dictionary.', 'Английский словарь.']],
    'die': [['Plants die without water.', 'Растения умирают без воды.']],
    'diet': [['A healthy diet.', 'Здоровая диета.']],
    'different': [['A different idea.', 'Другая идея.']],
    'difficult': [['A difficult question.', 'Трудный вопрос.']],
    'dinner': [['Have dinner at seven.', 'Поужинай в семь.']],
    'direct': [['A direct flight.', 'Прямой рейс.']],
    'direction': [['Wrong direction.', 'Неверное направление.']],
    'director': [['The company director.', 'Директор компании.']],
    'dirty': [['Dirty hands.', 'Грязные руки.']],
    'disagree': [['I disagree with you.', 'Я с тобой не согласен.']],
    'disappear': [['The sun disappeared.', 'Солнце исчезло.']],
    'discover': [['Discover new places.', 'Открывай новые места.']],
    'discuss': [['Let us discuss it.', 'Давай обсудим это.']],
    'disease': [['A serious disease.', 'Серьёзная болезнь.']],
    'dish': [['A delicious dish.', 'Вкусное блюдо.']],
    'distance': [['A long distance.', 'Долгое расстояние.']],
    'divide': [['Divide into two parts.', 'Раздели на две части.']],
    'do': [['What do you do?', 'Чем ты занимаешься?']],
    'doctor': [['Go to the doctor.', 'Иди к врачу.']],
    'dog': [['My dog is friendly.', 'Моя собака дружелюбная.']],
    'dollar': [['Five dollars.', 'Пять долларов.']],
    'door': [['Open the door.', 'Открой дверь.']],
    'double': [['A double room.', 'Двухместный номер.']],
    'doubt': [['No doubt.', 'Без сомнения.']],
    'down': [['Sit down.', 'Сядь.']],
    'dozen': [['A dozen eggs.', 'Дюжина яиц.']],
    'draw': [['Draw a cat.', 'Нарисуй кошку.']],
    'dream': [['A sweet dream.', 'Сладкий сон.']],
    'dress': [['A beautiful dress.', 'Красивое платье.']],
    'drink': [['Drink some water.', 'Выпей воды.']],
    'drive': [['Drive slowly.', 'Вези медленно.']],
    'driver': [['The bus driver.', 'Водитель автобуса.']],
    'drop': [['Do not drop it.', 'Не урони это.']],
    'drug': [['Take the drug.', 'Прими лекарство.']],
    'dry': [['Dry clothes.', 'Сухая одежда.']],
    'duck': [['A white duck.', 'Белая утка.']],
    'during': [['During the day.', 'В течение дня.']],
    'duty': [['Your duty.', 'Твой долг.']],

    // ═══ E ═══
    'each': [['Each of us.', 'Каждый из нас.']],
    'ear': [['My ear hurts.', 'У меня болит ухо.']],
    'early': [['Wake up early.', 'Проснись рано.']],
    'earn': [['Earn money.', 'Зарабатывай деньги.']],
    'earth': [['The planet Earth.', 'Планета Земля.']],
    'east': [['The east side.', 'Восточная сторона.']],
    'easy': [['An easy task.', 'Лёгкая задача.']],
    'eat': [['Let us eat!', 'Давай есть!']],
    'edge': [['At the edge.', 'На краю.']],
    'education': [['A good education.', 'Хорошее образование.']],
    'effect': [['A strong effect.', 'Сильный эффект.']],
    'effort': [['Make an effort.', 'Приложи усилие.']],
    'egg': [['A boiled egg.', 'Варёное яйцо.']],
    'eight': [['Eight hours.', 'Восемь часов.']],
    'either': [['Either way.', 'В любом случае.']],
    'elderly': [['An elderly woman.', 'Пожилая женщина.']],
    'electricity': [['No electricity.', 'Нет электричества.']],
    'elephant': [['A big elephant.', 'Большой слон.']],
    'else': [['Anything else?', 'Что-нибудь ещё?']],
    'email': [['Send an email.', 'Отправь письмо по электронной почте.']],
    'emergency': [['An emergency call.', 'Экстренный вызов.']],
    'emotion': [['A strong emotion.', 'Сильная эмоция.']],
    'employ': [['They employ many people.', 'Они нанимают много людей.']],
    'employee': [['A new employee.', 'Новый сотрудник.']],
    'empty': [['An empty room.', 'Пустая комната.']],
    'encourage': [['Encourage your friend.', 'Поддержи своего друга.']],
    'end': [['The end of the film.', 'Конец фильма.']],
    'enemy': [['An old enemy.', 'Старый враг.']],
    'energy': [['Clean energy.', 'Чистая энергия.']],
    'engine': [['A car engine.', 'Двигатель машины.']],
    'engineer': [['He is an engineer.', 'Он инженер.']],
    'enjoy': [['Enjoy your meal!', 'Приятного аппетита!']],
    'enough': [['That is enough.', 'Этого достаточно.']],
    'enter': [['Enter the room.', 'Войди в комнату.']],
    'entire': [['The entire world.', 'Весь мир.']],
    'entrance': [['The main entrance.', 'Главный вход.']],
    'environment': [['Protect the environment.', 'Защищай окружающую среду.']],
    'equal': [['Equal rights.', 'Равные права.']],
    'equipment': [['New equipment.', 'Новое оборудование.']],
    'error': [['A small error.', 'Маленькая ошибка.']],
    'escape': [['Escape the danger.', 'Спасайся от опасности.']],
    'especially': [['Especially for you.', 'Специально для тебя.']],
    'essay': [['Write an essay.', 'Напиши эссе.']],
    'even': [['Even a child can do it.', 'Даже ребёнок может это сделать.']],
    'evening': [['Good evening!', 'Добрый вечер!']],
    'event': [['A big event.', 'Большое событие.']],
    'ever': [['Have you ever been there?', 'Ты когда-нибудь там был?']],
    'every': [['Every day.', 'Каждый день.']],
    'everybody': [['Everybody knows it.', 'Все это знают.']],
    'everyone': [['Everyone is here.', 'Все здесь.']],
    'everything': [['Everything is fine.', 'Всё хорошо.']],
    'everywhere': [['I looked everywhere.', 'Я искал везде.']],
    'evidence': [['Strong evidence.', 'Сильное доказательство.']],
    'exact': [['The exact time.', 'Точное время.']],
    'exam': [['Pass the exam.', 'Сдай экзамен.']],
    'example': [['For example.', 'Например.']],
    'excellent': [['Excellent work!', 'Отличная работа!']],
    'except': [['Everyone except me.', 'Все, кроме меня.']],
    'exchange': [['Exchange money.', 'Обменяй деньги.']],
    'excited': [['I am excited.', 'Я взволнован.']],
    'exciting': [['An exciting story.', 'Увлекательная история.']],
    'excuse': [['Excuse me.', 'Извините.']],
    'exercise': [['Do exercise every day.', 'Занимайся каждый день.']],
    'exhibition': [['An art exhibition.', 'Выставка искусства.']],
    'exit': [['The emergency exit.', 'Запасной выход.']],
    'expect': [['I expect good news.', 'Я ожидаю хороших новостей.']],
    'expensive': [['An expensive car.', 'Дорогая машина.']],
    'experience': [['Work experience.', 'Опыт работы.']],
    'experiment': [['A science experiment.', 'Научный эксперимент.']],
    'expert': [['A computer expert.', 'Эксперт по компьютерам.']],
    'explain': [['Explain the rule.', 'Объясни правило.']],
    'explosion': [['A loud explosion.', 'Громкий взрыв.']],
    'export': [['Export cars.', 'Экспортируй машины.']],
    'express': [['Express your feelings.', 'Выражай свои чувства.']],
    'extend': [['Extend the deadline.', 'Продли срок.']],
    'extra': [['An extra chair.', 'Дополнительный стул.']],
    'eye': [['Close your eyes.', 'Закрой глаза.']],

    // ═══ F ═══
    'face': [['Wash your face.', 'Умой лицо.']],
    'fact': [['In fact.', 'На самом деле.']],
    'factory': [['A car factory.', 'Автомобильный завод.']],
    'fail': [['Do not fail.', 'Не потерпи неудачу.']],
    'fair': [['A fair game.', 'Честная игра.']],
    'fall': [['Do not fall.', 'Не упади.']],
    'false': [['A false answer.', 'Неверный ответ.']],
    'family': [['My family is big.', 'Моя семья большая.']],
    'famous': [['A famous singer.', 'Известный певец.']],
    'fan': [['A football fan.', 'Футбольный болельщик.']],
    'fantastic': [['A fantastic idea!', 'Фантастическая идея!']],
    'far': [['How far is it?', 'Как далеко это?']],
    'farm': [['A small farm.', 'Маленькая ферма.']],
    'farmer': [['He is a farmer.', 'Он фермер.']],
    'fashion': [['New fashion.', 'Новая мода.']],
    'fast': [['A fast car.', 'Быстрая машина.']],
    'fat': [['A fat cat.', 'Толстая кошка.']],
    'father': [['My father is a doctor.', 'Мой отец врач.']],
    'favourite': [['My favourite colour.', 'Мой любимый цвет.']],
    'fear': [['No fear.', 'Без страха.']],
    'feature': [['An important feature.', 'Важная особенность.']],
    'feed': [['Feed the cat.', 'Покорми кошку.']],
    'feel': [['I feel good.', 'Я чувствую себя хорошо.']],
    'feeling': [['A strange feeling.', 'Странное чувство.']],
    'female': [['A female doctor.', 'Женщина-врач.']],
    'fence': [['A wooden fence.', 'Деревянный забор.']],
    'festival': [['A music festival.', 'Музыкальный фестиваль.']],
    'fever': [['A high fever.', 'Высокая температура.']],
    'few': [['A few minutes.', 'Несколько минут.']],
    'field': [['A green field.', 'Зелёное поле.']],
    'fight': [['Do not fight.', 'Не дерись.']],
    'figure': [['A good figure.', 'Хорошая фигура.']],
    'fill': [['Fill the glass.', 'Наполни стакан.']],
    'film': [['A good film.', 'Хороший фильм.']],
    'final': [['The final test.', 'Финальный тест.']],
    'finally': [['Finally, we are here!', 'Наконец, мы здесь!']],
    'find': [['Find your keys.', 'Найди свои ключи.']],
    'fine': [['I am fine.', 'Я в порядке.']],
    'finger': [['My finger hurts.', 'У меня болит палец.']],
    'finish': [['Finish your work.', 'Закончи работу.']],
    'fire': [['A big fire.', 'Большой огонь.']],
    'first': [['The first day.', 'Первый день.']],
    'fish': [['A big fish.', 'Большая рыба.']],
    'fit': [['Keep fit.', 'Будь в форме.']],
    'five': [['Five minutes.', 'Пять минут.']],
    'fix': [['Fix the car.', 'Почини машину.']],
    'flag': [['The Russian flag.', 'Российский флаг.']],
    'flat': [['A flat surface.', 'Плоская поверхность.']],
    'flight': [['A long flight.', 'Долгий полёт.']],
    'floor': [['On the floor.', 'На полу.']],
    'flower': [['A beautiful flower.', 'Красивый цветок.']],
    'fly': [['Birds fly.', 'Птицы летают.']],
    'focus': [['Focus on your work.', 'Сосредоточься на работе.']],
    'follow': [['Follow me.', 'Следуй за мной.']],
    'food': [['Delicious food.', 'Вкусная еда.']],
    'foot': [['My foot hurts.', 'У меня болит нога.']],
    'football': [['Play football.', 'Играй в футбол.']],
    'for': [['A gift for you.', 'Подарок для тебя.']],
    'force': [['A strong force.', 'Сильная сила.']],
    'foreign': [['A foreign language.', 'Иностранный язык.']],
    'forest': [['A dark forest.', 'Тёмный лес.']],
    'forget': [['Do not forget.', 'Не забудь.']],
    'forgive': [['Forgive me.', 'Прости меня.']],
    'fork': [['Use a fork.', 'Используй вилку.']],
    'form': [['Fill the form.', 'Заполни форму.']],
    'forward': [['Go forward.', 'Иди вперёд.']],
    'four': [['Four seasons.', 'Четыре сезона.']],
    'free': [['Free time.', 'Свободное время.']],
    'freedom': [['Freedom of speech.', 'Свобода слова.']],
    'fresh': [['Fresh bread.', 'Свежий хлеб.']],
    'friend': [['My best friend.', 'Мой лучший друг.']],
    'friendly': [['A friendly dog.', 'Дружелюбная собака.']],
    'friendship': [['A true friendship.', 'Настоящая дружба.']],
    'from': [['I am from Russia.', 'Я из России.']],
    'front': [['In front of the house.', 'Перед домом.']],
    'fruit': [['Fresh fruit.', 'Свежие фрукты.']],
    'full': [['A full glass.', 'Полный стакан.']],
    'fun': [['Have fun!', 'Веселись!']],
    'funny': [['A funny story.', 'Смешная история.']],
    'furniture': [['New furniture.', 'Новая мебель.']],
    'future': [['The future is bright.', 'Будущее светлое.']],

    // ═══ G ═══
    'game': [['A computer game.', 'Компьютерная игра.']],
    'garden': [['A beautiful garden.', 'Красивый сад.']],
    'gas': [['A gas station.', 'Заправка.']],
    'gate': [['Close the gate.', 'Закрой ворота.']],
    'gather': [['Gather the team.', 'Собери команду.']],
    'general': [['A general rule.', 'Общее правило.']],
    'generation': [['A new generation.', 'Новое поколение.']],
    'gentleman': [['A real gentleman.', 'Настоящий джентльмен.']],
    'geography': [['I study geography.', 'Я изучаю географию.']],
    'get': [['Get some sleep.', 'Поспи немного.']],
    'gift': [['A birthday gift.', 'Подарок на день рождения.']],
    'girl': [['A young girl.', 'Молодая девушка.']],
    'give': [['Give me a pen.', 'Дай мне ручку.']],
    'glad': [['I am glad to see you.', 'Я рад тебя видеть.']],
    'glass': [['A glass of water.', 'Стакан воды.']],
    'glasses': [['My new glasses.', 'Мои новые очки.']],
    'glove': [['A warm glove.', 'Тёплая перчатка.']],
    'glue': [['Use glue.', 'Используй клей.']],
    'go': [['Let us go!', 'Пойдём!']],
    'goal': [['A clear goal.', 'Ясная цель.']],
    'god': [['Oh my God!', 'О боже!']],
    'gold': [['A gold ring.', 'Золотое кольцо.']],
    'good': [['A good idea.', 'Хорошая идея.']],
    'goodbye': [['Goodbye! See you!', 'До свидания! Увидимся!']],
    'government': [['The government decides.', 'Правительство решает.']],
    'grandfather': [['My grandfather is old.', 'Мой дедушка старый.']],
    'grandmother': [['My grandmother cooks well.', 'Моя бабушка хорошо готовит.']],
    'grass': [['Green grass.', 'Зелёная трава.']],
    'grateful': [['I am grateful.', 'Я благодарен.']],
    'great': [['A great day.', 'Великий день.']],
    'green': [['Green leaves.', 'Зелёные листья.']],
    'grey': [['A grey sky.', 'Серое небо.']],
    'ground': [['On the ground.', 'На земле.']],
    'group': [['A small group.', 'Маленькая группа.']],
    'grow': [['Plants grow fast.', 'Растения растут быстро.']],
    'growth': [['Economic growth.', 'Экономический рост.']],
    'guard': [['A security guard.', 'Охранник.']],
    'guess': [['Guess my name.', 'Угадай моё имя.']],
    'guest': [['An important guest.', 'Важный гость.']],
    'guide': [['A tour guide.', 'Тургид.']],
    'guilty': [['I am guilty.', 'Я виноват.']],
    'guitar': [['Play the guitar.', 'Играй на гитаре.']],
    'gun': [['A toy gun.', 'Игрушечный пистолет.']],
    'guy': [['A nice guy.', 'Хороший парень.']],

    // ═══ H ═══
    'habit': [['A bad habit.', 'Плохая привычка.']],
    'hair': [['Her hair is long.', 'У неё длинные волосы.']],
    'half': [['Half an hour.', 'Полчаса.']],
    'hall': [['A big hall.', 'Большой зал.']],
    'hand': [['Wash your hands.', 'Помой руки.']],
    'handsome': [['A handsome man.', 'Красивый мужчина.']],
    'happen': [['What happened?', 'Что случилось?']],
    'happiness': [['True happiness.', 'Настоящее счастье.']],
    'happy': [['I am happy.', 'Я счастлив.']],
    'hard': [['A hard task.', 'Тяжёлая задача.']],
    'hardly': [['I hardly know him.', 'Я его едва знаю.']],
    'hate': [['I hate lies.', 'Я ненавижу ложь.']],
    'have': [['I have a car.', 'У меня есть машина.']],
    'he': [['He is my friend.', 'Он мой друг.']],
    'head': [['My head hurts.', 'У меня болит голова.']],
    'headache': [['A bad headache.', 'Сильная головная боль.']],
    'health': [['Good health.', 'Хорошее здоровье.']],
    'healthy': [['Healthy food.', 'Здоровая еда.']],
    'hear': [['I hear you.', 'Я тебя слышу.']],
    'heart': [['My heart beats fast.', 'Моё сердце бьётся быстро.']],
    'heat': [['Summer heat.', 'Летняя жара.']],
    'heavy': [['A heavy bag.', 'Тяжёлая сумка.']],
    'height': [['What is your height?', 'Какой у тебя рост?']],
    'hello': [['Hello! How are you?', 'Привет! Как дела?']],
    'help': [['Can you help me?', 'Можешь мне помочь?']],
    'helpful': [['A helpful tip.', 'Полезный совет.']],
    'her': [['Her name is Anna.', 'Её зовут Анна.']],
    'here': [['Come here.', 'Иди сюда.']],
    'hero': [['A real hero.', 'Настоящий герой.']],
    'hide': [['Hide and seek.', 'Прятки.']],
    'high': [['A high mountain.', 'Высокая гора.']],
    'hill': [['A small hill.', 'Маленький холм.']],
    'him': [['Give it to him.', 'Дай это ему.']],
    'his': [['His car is new.', 'Его машина новая.']],
    'history': [['Study history.', 'Изучай историю.']],
    'hit': [['Do not hit me.', 'Не ударь меня.']],
    'hobby': [['My hobby is reading.', 'Моё хобби — чтение.']],
    'hold': [['Hold my hand.', 'Держи мою руку.']],
    'hole': [['A small hole.', 'Маленькая дыра.']],
    'holiday': [['Summer holiday.', 'Летний отпуск.']],
    'home': [['I am at home.', 'Я дома.']],
    'homework': [['Do your homework.', 'Сделай домашнюю работу.']],
    'honest': [['An honest man.', 'Честный человек.']],
    'honey': [['Sweet honey.', 'Сладкий мёд.']],
    'hope': [['I hope so.', 'Надеюсь, что так.']],
    'horrible': [['A horrible film.', 'Ужасный фильм.']],
    'horse': [['The horse is running.', 'Лошадь бежит.']],
    'hospital': [['Go to the hospital.', 'Иди в больницу.']],
    'hot': [['Hot tea.', 'Горячий чай.']],
    'hotel': [['A nice hotel.', 'Хороший отель.']],
    'hour': [['One hour.', 'Один час.']],
    'house': [['My house is big.', 'Мой дом большой.']],
    'how': [['How are you?', 'Как дела?']],
    'however': [['However, I agree.', 'Однако я согласен.']],
    'huge': [['A huge elephant.', 'Огромный слон.']],
    'human': [['A human being.', 'Человеческое существо.']],
    'humour': [['A good sense of humour.', 'Хорошее чувство юмора.']],
    'hundred': [['A hundred dollars.', 'Сто долларов.']],
    'hungry': [['I am hungry.', 'Я голоден.']],
    'hunt': [['They hunt animals.', 'Они охотятся на животных.']],
    'hurry': [['Hurry up!', 'Поторопись!']],
    'hurt': [['My leg hurts.', 'У меня болит нога.']],
    'husband': [['My husband is kind.', 'Мой муж добрый.']],

    // ═══ I ═══
    'I': [['I am a student.', 'Я студент.']],
    'ice': [['Cold ice.', 'Холодный лёд.']],
    'idea': [['A great idea!', 'Отличная идея!']],
    'if': [['If you want.', 'Если хочешь.']],
    'ignore': [['Do not ignore me.', 'Не игнорируй меня.']],
    'ill': [['I am ill.', 'Я болен.']],
    'illness': [['A serious illness.', 'Серьёзная болезнь.']],
    'imagine': [['Imagine this.', 'Представь это.']],
    'important': [['An important meeting.', 'Важная встреча.']],
    'impossible': [['It is impossible.', 'Это невозможно.']],
    'impress': [['Impress your boss.', 'Впечатли своего начальника.']],
    'improve': [['Improve your English.', 'Улучшай свой английский.']],
    'in': [['In the box.', 'В коробке.']],
    'include': [['Include me too.', 'Включи меня тоже.']],
    'income': [['A good income.', 'Хороший доход.']],
    'increase': [['Increase the price.', 'Увеличь цену.']],
    'industry': [['Heavy industry.', 'Тяжёлая промышленность.']],
    'influence': [['A strong influence.', 'Сильное влияние.']],
    'inform': [['Inform me later.', 'Сообщи мне позже.']],
    'information': [['Useful information.', 'Полезная информация.']],
    'inside': [['Inside the house.', 'Внутри дома.']],
    'instead': [['Take this instead.', 'Возьми это вместо.']],
    'instruction': [['Read the instructions.', 'Прочитай инструкции.']],
    'instrument': [['A musical instrument.', 'Музыкальный инструмент.']],
    'insurance': [['Car insurance.', 'Страховка машины.']],
    'intelligent': [['An intelligent student.', 'Умный студент.']],
    'interest': [['No interest.', 'Нет интереса.']],
    'interested': [['I am interested.', 'Мне интересно.']],
    'interesting': [['An interesting book.', 'Интересная книга.']],
    'international': [['An international company.', 'Международная компания.']],
    'internet': [['Fast internet.', 'Быстрый интернет.']],
    'interview': [['A job interview.', 'Собеседование.']],
    'into': [['Come into the room.', 'Зайди в комнату.']],
    'introduce': [['Introduce yourself.', 'Представься.']],
    'invent': [['Invent something new.', 'Изобрети что-то новое.']],
    'invitation': [['A wedding invitation.', 'Приглашение на свадьбу.']],
    'invite': [['Invite your friends.', 'Пригласи друзей.']],
    'island': [['A small island.', 'Маленький остров.']],
    'it': [['It is a cat.', 'Это кошка.']],
    'item': [['A small item.', 'Маленький предмет.']],

    // ═══ J ═══
    'jacket': [['A warm jacket.', 'Тёплая куртка.']],
    'jam': [['Strawberry jam.', 'Клубничное варенье.']],
    'jeans': [['Blue jeans.', 'Синие джинсы.']],
    'job': [['A good job.', 'Хорошая работа.']],
    'join': [['Join us!', 'Присоединяйся!']],
    'joke': [['A funny joke.', 'Смешная шутка.']],
    'journey': [['A long journey.', 'Долгое путешествие.']],
    'joy': [['A lot of joy.', 'Много радости.']],
    'judge': [['The judge decides.', 'Судья решает.']],
    'juice': [['Orange juice.', 'Апельсиновый сок.']],
    'jump': [['Jump higher!', 'Прыгай выше!']],
    'just': [['Just a moment.', 'Один момент.']],

    // ═══ K ═══
    'keep': [['Keep the change.', 'Оставь сдачу.']],
    'key': [['Where is my key?', 'Где мой ключ?']],
    'keyboard': [['A new keyboard.', 'Новая клавиатура.']],
    'kick': [['Kick the ball.', 'Пни мяч.']],
    'kid': [['A little kid.', 'Маленький ребёнок.']],
    'kill': [['Do not kill animals.', 'Не убивай животных.']],
    'kilometre': [['Ten kilometres.', 'Десять километров.']],
    'kind': [['A kind person.', 'Добрый человек.']],
    'king': [['A wise king.', 'Мудрый король.']],
    'kiss': [['Kiss me.', 'Поцелуй меня.']],
    'kitchen': [['A big kitchen.', 'Большая кухня.']],
    'knee': [['My knee hurts.', 'У меня болит колено.']],
    'knife': [['A sharp knife.', 'Острый нож.']],
    'knock': [['Knock on the door.', 'Постучи в дверь.']],
    'know': [['I know him.', 'Я его знаю.']],
    'knowledge': [['Deep knowledge.', 'Глубокие знания.']],

    // ═══ L ═══
    'lady': [['An old lady.', 'Пожилая леди.']],
    'lake': [['A beautiful lake.', 'Красивое озеро.']],
    'lamp': [['Turn on the lamp.', 'Включи лампу.']],
    'land': [['Fertile land.', 'Плодородная земля.']],
    'language': [['A foreign language.', 'Иностранный язык.']],
    'laptop': [['A new laptop.', 'Новый ноутбук.']],
    'large': [['A large room.', 'Большая комната.']],
    'last': [['The last day.', 'Последний день.']],
    'late': [['Do not be late.', 'Не опаздывай.']],
    'later': [['See you later.', 'Увидимся позже.']],
    'laugh': [['Laugh out loud.', 'Смейся громко.']],
    'law': [['Obey the law.', 'Соблюдай закон.']],
    'lawyer': [['A good lawyer.', 'Хороший юрист.']],
    'lazy': [['A lazy cat.', 'Ленивая кошка.']],
    'lead': [['Lead the way.', 'Веди дорогу.']],
    'leader': [['A strong leader.', 'Сильный лидер.']],
    'leaf': [['A green leaf.', 'Зелёный лист.']],
    'learn': [['Learn English.', 'Учи английский.']],
    'least': [['At least.', 'По крайней мере.']],
    'leather': [['A leather bag.', 'Кожаная сумка.']],
    'leave': [['Leave me alone.', 'Оставь меня в покое.']],
    'left': [['Turn left.', 'Поверни налево.']],
    'leg': [['My leg hurts.', 'У меня болит нога.']],
    'lemon': [['A sour lemon.', 'Кислый лимон.']],
    'lend': [['Lend me a pen.', 'Одолжи мне ручку.']],
    'length': [['The length of the room.', 'Длина комнаты.']],
    'less': [['Less sugar, please.', 'Меньше сахара, пожалуйста.']],
    'lesson': [['An English lesson.', 'Урок английского.']],
    'letter': [['Write a letter.', 'Напиши письмо.']],
    'level': [['A high level.', 'Высокий уровень.']],
    'library': [['Go to the library.', 'Иди в библиотеку.']],
    'life': [['Life is beautiful.', 'Жизнь прекрасна.']],
    'lift': [['Lift the box.', 'Подними коробку.']],
    'light': [['A bright light.', 'Яркий свет.']],
    'like': [['I like coffee.', 'Я люблю кофе.']],
    'limit': [['A speed limit.', 'Ограничение скорости.']],
    'line': [['A long line.', 'Длинная очередь.']],
    'lion': [['A big lion.', 'Большой лев.']],
    'lip': [['My lips are dry.', 'У меня сухие губы.']],
    'list': [['A shopping list.', 'Список покупок.']],
    'listen': [['Listen to me.', 'Слушай меня.']],
    'literature': [['English literature.', 'Английская литература.']],
    'little': [['A little cat.', 'Маленькая кошка.']],
    'live': [['I live in Moscow.', 'Я живу в Москве.']],
    'local': [['Local food.', 'Местная еда.']],
    'lock': [['Lock the door.', 'Закрой дверь на замок.']],
    'lonely': [['A lonely man.', 'Одинокий человек.']],
    'long': [['A long road.', 'Длинная дорога.']],
    'look': [['Look at me.', 'Посмотри на меня.']],
    'lose': [['Do not lose it.', 'Не потеряй это.']],
    'loss': [['A big loss.', 'Большая потеря.']],
    'loud': [['A loud noise.', 'Громкий шум.']],
    'love': [['I love you.', 'Я тебя люблю.']],
    'lovely': [['A lovely day.', 'Прекрасный день.']],
    'low': [['A low price.', 'Низкая цена.']],
    'luck': [['Good luck!', 'Удачи!']],
    'lucky': [['A lucky day.', 'Счастливый день.']],
    'luggage': [['My luggage is heavy.', 'Мой багаж тяжёлый.']],
    'lunch': [['Have lunch.', 'Пообедай.']],

    // ═══ M ═══
    'machine': [['A washing machine.', 'Стиральная машина.']],
    'magazine': [['A fashion magazine.', 'Модный журнал.']],
    'mail': [['Check the mail.', 'Проверь почту.']],
    'main': [['The main street.', 'Главная улица.']],
    'make': [['Make a cake.', 'Сделай торт.']],
    'man': [['A tall man.', 'Высокий мужчина.']],
    'manage': [['Manage your time.', 'Управляй своим временем.']],
    'manager': [['The sales manager.', 'Менеджер по продажам.']],
    'many': [['Many people.', 'Много людей.']],
    'map': [['A world map.', 'Карта мира.']],
    'mark': [['A good mark.', 'Хорошая оценка.']],
    'market': [['The local market.', 'Местный рынок.']],
    'marriage': [['A happy marriage.', 'Счастливый брак.']],
    'marry': [['Will you marry me?', 'Ты выйдешь за меня?']],
    'match': [['A football match.', 'Футбольный матч.']],
    'material': [['A new material.', 'Новый материал.']],
    'matter': [['What is the matter?', 'В чём дело?']],
    'maybe': [['Maybe tomorrow.', 'Может быть, завтра.']],
    'me': [['Give it to me.', 'Дай это мне.']],
    'meal': [['A tasty meal.', 'Вкусная еда.']],
    'mean': [['What do you mean?', 'Что ты имеешь в виду?']],
    'meaning': [['A deep meaning.', 'Глубокий смысл.']],
    'measure': [['Measure the table.', 'Измерь стол.']],
    'meat': [['Fresh meat.', 'Свежее мясо.']],
    'medical': [['Medical help.', 'Медицинская помощь.']],
    'medicine': [['Take your medicine.', 'Прими лекарство.']],
    'meet': [['Nice to meet you.', 'Приятно познакомиться.']],
    'meeting': [['An important meeting.', 'Важная встреча.']],
    'member': [['A team member.', 'Член команды.']],
    'memory': [['A good memory.', 'Хорошая память.']],
    'mention': [['Do not mention it.', 'Не упоминай это.']],
    'menu': [['Look at the menu.', 'Посмотри меню.']],
    'message': [['Send me a message.', 'Отправь мне сообщение.']],
    'metal': [['A metal box.', 'Металлическая коробка.']],
    'method': [['A new method.', 'Новый метод.']],
    'metre': [['One metre.', 'Один метр.']],
    'middle': [['In the middle.', 'В середине.']],
    'milk': [['A glass of milk.', 'Стакан молока.']],
    'million': [['A million people.', 'Миллион людей.']],
    'mind': [['Peace of mind.', 'Спокойствие.']],
    'mine': [['That book is mine.', 'Та книга моя.']],
    'minute': [['One minute.', 'Одна минута.']],
    'mirror': [['Look in the mirror.', 'Посмотри в зеркало.']],
    'miss': [['I miss you.', 'Я скучаю по тебе.']],
    'mistake': [['A small mistake.', 'Маленькая ошибка.']],
    'mix': [['Mix the ingredients.', 'Смешай ингредиенты.']],
    'model': [['A new model.', 'Новая модель.']],
    'modern': [['A modern house.', 'Современный дом.']],
    'moment': [['Wait a moment.', 'Подожди момент.']],
    'money': [['I need money.', 'Мне нужны деньги.']],
    'monkey': [['A funny monkey.', 'Смешная обезьяна.']],
    'month': [['Next month.', 'В следующем месяце.']],
    'mood': [['A good mood.', 'Хорошее настроение.']],
    'moon': [['The moon is bright.', 'Луна яркая.']],
    'more': [['More water, please.', 'Больше воды, пожалуйста.']],
    'morning': [['Good morning!', 'Доброе утро!']],
    'most': [['Most people.', 'Большинство людей.']],
    'mother': [['My mother is kind.', 'Моя мама добрая.']],
    'mountain': [['A high mountain.', 'Высокая гора.']],
    'mouse': [['A small mouse.', 'Маленькая мышь.']],
    'mouth': [['Open your mouth.', 'Открой рот.']],
    'move': [['Move the chair.', 'Передвинь стул.']],
    'movie': [['A good movie.', 'Хороший фильм.']],
    'much': [['How much?', 'Сколько?']],
    'music': [['I love music.', 'Я люблю музыку.']],
    'musician': [['A talented musician.', 'Талантливый музыкант.']],
    'must': [['You must go.', 'Ты должен идти.']],
    'my': [['My house.', 'Мой дом.']],
    'myself': [['I did it myself.', 'Я сделал это сам.']],
    'mystery': [['A big mystery.', 'Большая тайна.']]
};
// ═══════════════════════════════════════════════
// ПРОДОЛЖЕНИЕ SENTENCES (N–Z)
// ⚠️ Вставьте эти строки ВНУТРЬ объекта SENTENCES из части 1,
//    то есть ПЕРЕД закрывающей }; после 'mystery'
// ═══════════════════════════════════════════════

    // ═══ N ═══
    'nail': [['Cut your nails.', 'Подстриги ногти.']],
    'name': [['What is your name?', 'Как тебя зовут?']],
    'narrow': [['A narrow street.', 'Узкая улица.']],
    'nation': [['A great nation.', 'Великая нация.']],
    'national': [['A national holiday.', 'Национальный праздник.']],
    'natural': [['Natural beauty.', 'Природная красота.']],
    'nature': [['I love nature.', 'Я люблю природу.']],
    'near': [['A near shop.', 'Ближний магазин.']],
    'nearly': [['Nearly finished.', 'Почти закончил.']],
    'necessary': [['It is necessary.', 'Это необходимо.']],
    'neck': [['My neck hurts.', 'У меня болит шея.']],
    'need': [['I need help.', 'Мне нужна помощь.']],
    'neighbour': [['My neighbour is friendly.', 'Мой сосед дружелюбный.']],
    'neither': [['Neither of them.', 'Ни один из них.']],
    'nervous': [['I am nervous.', 'Я нервничаю.']],
    'never': [['Never give up.', 'Никогда не сдавайся.']],
    'new': [['A new phone.', 'Новый телефон.']],
    'news': [['Good news!', 'Хорошие новости!']],
    'newspaper': [['Read the newspaper.', 'Читай газету.']],
    'next': [['Next week.', 'На следующей неделе.']],
    'nice': [['A nice day.', 'Хороший день.']],
    'night': [['Good night!', 'Спокойной ночи!']],
    'nine': [['Nine hours.', 'Девять часов.']],
    'no': [['No, thank you.', 'Нет, спасибо.']],
    'nobody': [['Nobody is home.', 'Никого нет дома.']],
    'noise': [['A loud noise.', 'Громкий шум.']],
    'none': [['None of us.', 'Никто из нас.']],
    'noon': [['It is noon.', 'Сейчас полдень.']],
    'normal': [['A normal day.', 'Обычный день.']],
    'north': [['The north wind.', 'Северный ветер.']],
    'nose': [['My nose is cold.', 'У меня холодный нос.']],
    'not': [['I am not ready.', 'Я не готов.']],
    'note': [['Take a note.', 'Запиши.']],
    'nothing': [['Nothing to do.', 'Нечего делать.']],
    'notice': [['I notice it.', 'Я замечаю это.']],
    'novel': [['A good novel.', 'Хороший роман.']],
    'now': [['Now is the time.', 'Сейчас время.']],
    'nowhere': [['Nowhere to go.', 'Негде идти.']],
    'number': [['What is your number?', 'Какой у тебя номер?']],
    'nurse': [['The nurse is kind.', 'Медсестра добрая.']],
    'nut': [['A small nut.', 'Маленький орех.']],

    // ═══ O ═══
    'obey': [['Obey your parents.', 'Слушайся родителей.']],
    'object': [['A strange object.', 'Странный объект.']],
    'ocean': [['The deep ocean.', 'Глубокий океан.']],
    'of': [['A cup of tea.', 'Чашка чая.']],
    'off': [['Turn off the light.', 'Выключи свет.']],
    'offer': [['A good offer.', 'Хорошее предложение.']],
    'office': [['Go to the office.', 'Иди в офис.']],
    'officer': [['A police officer.', 'Полицейский.']],
    'official': [['An official document.', 'Официальный документ.']],
    'often': [['I often read.', 'Я часто читаю.']],
    'oil': [['Olive oil.', 'Оливковое масло.']],
    'old': [['An old house.', 'Старый дом.']],
    'on': [['The book is on the table.', 'Книга на столе.']],
    'once': [['Only once.', 'Только один раз.']],
    'one': [['One apple.', 'Одно яблоко.']],
    'onion': [['A red onion.', 'Красный лук.']],
    'only': [['Only you.', 'Только ты.']],
    'open': [['Open the window.', 'Открой окно.']],
    'operation': [['A serious operation.', 'Серьёзная операция.']],
    'opinion': [['In my opinion.', 'По моему мнению.']],
    'opposite': [['The opposite side.', 'Противоположная сторона.']],
    'or': [['Tea or coffee?', 'Чай или кофе?']],
    'orange': [['A sweet orange.', 'Сладкий апельсин.']],
    'order': [['Order a pizza.', 'Закажи пиццу.']],
    'ordinary': [['An ordinary day.', 'Обычный день.']],
    'organize': [['Organize a party.', 'Организуй вечеринку.']],
    'other': [['The other side.', 'Другая сторона.']],
    'our': [['Our house.', 'Наш дом.']],
    'out': [['Go out!', 'Выйди!']],
    'outside': [['Play outside.', 'Играй на улице.']],
    'over': [['Over the bridge.', 'Через мост.']],
    'own': [['My own room.', 'Моя собственная комната.']],

    // ═══ P ═══
    'pack': [['Pack your bags.', 'Собери чемоданы.']],
    'page': [['Turn the page.', 'Переверни страницу.']],
    'pain': [['A strong pain.', 'Сильная боль.']],
    'paint': [['Paint the wall.', 'Покрась стену.']],
    'painting': [['A beautiful painting.', 'Красивая картина.']],
    'pair': [['A pair of shoes.', 'Пара обуви.']],
    'palace': [['A royal palace.', 'Королевский дворец.']],
    'pale': [['A pale face.', 'Бледное лицо.']],
    'paper': [['A piece of paper.', 'Лист бумаги.']],
    'parent': [['My parents are kind.', 'Мои родители добрые.']],
    'park': [['Go to the park.', 'Иди в парк.']],
    'part': [['A big part.', 'Большая часть.']],
    'particular': [['A particular case.', 'Конкретный случай.']],
    'partner': [['A business partner.', 'Деловой партнёр.']],
    'party': [['A birthday party.', 'День рождения.']],
    'pass': [['Pass the salt.', 'Передай соль.']],
    'passenger': [['The passenger is waiting.', 'Пассажир ждёт.']],
    'passport': [['Show your passport.', 'Покажи паспорт.']],
    'past': [['In the past.', 'В прошлом.']],
    'path': [['A narrow path.', 'Узкая тропинка.']],
    'patient': [['Be patient.', 'Будь терпелив.']],
    'pattern': [['A nice pattern.', 'Красивый узор.']],
    'pay': [['Pay the bill.', 'Оплати счёт.']],
    'peace': [['World peace.', 'Миру мир.']],
    'pen': [['A blue pen.', 'Синяя ручка.']],
    'pencil': [['A sharp pencil.', 'Острый карандаш.']],
    'people': [['Many people.', 'Много людей.']],
    'pepper': [['Black pepper.', 'Чёрный перец.']],
    'per': [['Per day.', 'В день.']],
    'perfect': [['A perfect day.', 'Идеальный день.']],
    'perform': [['Perform on stage.', 'Выступай на сцене.']],
    'perhaps': [['Perhaps tomorrow.', 'Возможно, завтра.']],
    'period': [['A short period.', 'Короткий период.']],
    'permission': [['Ask for permission.', 'Спроси разрешения.']],
    'person': [['A good person.', 'Хороший человек.']],
    'personal': [['A personal question.', 'Личный вопрос.']],
    'pet': [['A small pet.', 'Маленький питомец.']],
    'phone': [['Answer the phone.', 'Ответь на телефон.']],
    'photo': [['Take a photo.', 'Сделай фото.']],
    'physics': [['I study physics.', 'Я изучаю физику.']],
    'piano': [['Play the piano.', 'Играй на пианино.']],
    'pick': [['Pick a card.', 'Выбери карту.']],
    'picture': [['A nice picture.', 'Хорошая картина.']],
    'piece': [['A piece of cake.', 'Кусок торта.']],
    'pig': [['A pink pig.', 'Розовая свинья.']],
    'pill': [['Take a pill.', 'Прими таблетку.']],
    'pilot': [['A good pilot.', 'Хороший пилот.']],
    'pink': [['A pink dress.', 'Розовое платье.']],
    'pipe': [['A water pipe.', 'Водопроводная труба.']],
    'pity': [['What a pity!', 'Как жаль!']],
    'pizza': [['A hot pizza.', 'Горячая пицца.']],
    'place': [['A nice place.', 'Хорошее место.']],
    'plan': [['A good plan.', 'Хороший план.']],
    'plane': [['A big plane.', 'Большой самолёт.']],
    'plant': [['Water the plant.', 'Полей растение.']],
    'plastic': [['A plastic bag.', 'Пластиковый пакет.']],
    'plate': [['A white plate.', 'Белая тарелка.']],
    'platform': [['On the platform.', 'На платформе.']],
    'play': [['Play with me.', 'Играй со мной.']],
    'player': [['A good player.', 'Хороший игрок.']],
    'pleasant': [['A pleasant day.', 'Приятный день.']],
    'please': [['Please help me.', 'Пожалуйста, помоги мне.']],
    'pleased': [['I am pleased.', 'Я доволен.']],
    'pleasure': [['With pleasure.', 'С удовольствием.']],
    'plenty': [['Plenty of time.', 'Много времени.']],
    'plus': [['Two plus two.', 'Два плюс два.']],
    'pocket': [['In my pocket.', 'В моём кармане.']],
    'poem': [['A beautiful poem.', 'Красивое стихотворение.']],
    'point': [['A good point.', 'Хорошая мысль.']],
    'poison': [['A strong poison.', 'Сильный яд.']],
    'police': [['Call the police.', 'Вызови полицию.']],
    'polite': [['A polite boy.', 'Вежливый мальчик.']],
    'politics': [['I follow politics.', 'Я слежу за политикой.']],
    'pool': [['A big pool.', 'Большой бассейн.']],
    'poor': [['A poor man.', 'Бедный человек.']],
    'popular': [['A popular song.', 'Популярная песня.']],
    'population': [['A large population.', 'Большое население.']],
    'pork': [['Fried pork.', 'Жареная свинина.']],
    'port': [['A sea port.', 'Морской порт.']],
    'position': [['A good position.', 'Хорошая позиция.']],
    'positive': [['Stay positive.', 'Оставайся позитивным.']],
    'possible': [['It is possible.', 'Это возможно.']],
    'post': [['Post a letter.', 'Отправь письмо.']],
    'potato': [['A big potato.', 'Большая картофелина.']],
    'pound': [['A pound of sugar.', 'Фунт сахара.']],
    'power': [['Great power.', 'Великая сила.']],
    'practical': [['A practical idea.', 'Практичная идея.']],
    'practice': [['Practice every day.', 'Занимайся каждый день.']],
    'praise': [['Praise your friend.', 'Хвали своего друга.']],
    'pray': [['Pray for peace.', 'Молись о мире.']],
    'prefer': [['I prefer tea.', 'Я предпочитаю чай.']],
    'prepare': [['Prepare dinner.', 'Приготовь ужин.']],
    'present': [['A nice present.', 'Хороший подарок.']],
    'president': [['The president spoke.', 'Президент выступил.']],
    'press': [['Press the button.', 'Нажми кнопку.']],
    'pretty': [['A pretty girl.', 'Хорошенькая девочка.']],
    'prevent': [['Prevent the problem.', 'Предотврати проблему.']],
    'price': [['A good price.', 'Хорошая цена.']],
    'pride': [['A matter of pride.', 'Дело гордости.']],
    'primary': [['Primary school.', 'Начальная школа.']],
    'print': [['Print the document.', 'Распечатай документ.']],
    'prison': [['A big prison.', 'Большая тюрьма.']],
    'private': [['A private room.', 'Отдельная комната.']],
    'prize': [['Win a prize.', 'Выиграй приз.']],
    'probably': [['Probably yes.', 'Наверное, да.']],
    'problem': [['A big problem.', 'Большая проблема.']],
    'process': [['A long process.', 'Долгий процесс.']],
    'produce': [['Produce cars.', 'Производи машины.']],
    'product': [['A new product.', 'Новый продукт.']],
    'profession': [['A good profession.', 'Хорошая профессия.']],
    'professor': [['The professor spoke.', 'Профессор выступил.']],
    'profit': [['A big profit.', 'Большая прибыль.']],
    'program': [['A useful program.', 'Полезная программа.']],
    'progress': [['Good progress.', 'Хороший прогресс.']],
    'project': [['A new project.', 'Новый проект.']],
    'promise': [['Promise me.', 'Обещай мне.']],
    'promote': [['Promote the product.', 'Продвигай продукт.']],
    'pronounce': [['Pronounce the word.', 'Произнеси слово.']],
    'proof': [['Strong proof.', 'Сильное доказательство.']],
    'proper': [['The proper way.', 'Правильный способ.']],
    'protect': [['Protect your family.', 'Защити свою семью.']],
    'proud': [['I am proud of you.', 'Я горжусь тобой.']],
    'prove': [['Prove it.', 'Докажи это.']],
    'provide': [['Provide food.', 'Обеспечь едой.']],
    'public': [['Public transport.', 'Общественный транспорт.']],
    'pull': [['Pull the door.', 'Тяни дверь.']],
    'pupil': [['A good pupil.', 'Хороший ученик.']],
    'purpose': [['A good purpose.', 'Хорошая цель.']],
    'purse': [['A leather purse.', 'Кожаный кошелёк.']],
    'push': [['Push the button.', 'Нажми кнопку.']],
    'put': [['Put it here.', 'Положи это сюда.']],

    // ═══ Q ═══
    'quality': [['Good quality.', 'Хорошее качество.']],
    'quantity': [['A large quantity.', 'Большое количество.']],
    'quarter': [['A quarter of an hour.', 'Четверть часа.']],
    'queen': [['A beautiful queen.', 'Красивая королева.']],
    'question': [['A good question.', 'Хороший вопрос.']],
    'queue': [['A long queue.', 'Длинная очередь.']],
    'quick': [['A quick answer.', 'Быстрый ответ.']],
    'quickly': [['Run quickly!', 'Беги быстро!']],
    'quiet': [['A quiet room.', 'Тихая комната.']],
    'quite': [['Quite good.', 'Довольно хорошо.']],
    'quiz': [['A short quiz.', 'Короткая викторина.']],

    // ═══ R ═══
    'race': [['A car race.', 'Автогонка.']],
    'radio': [['Turn on the radio.', 'Включи радио.']],
    'railway': [['A railway station.', 'Железнодорожная станция.']],
    'rain': [['Heavy rain.', 'Сильный дождь.']],
    'raise': [['Raise your hand.', 'Подними руку.']],
    'rare': [['A rare animal.', 'Редкое животное.']],
    'rather': [['Rather good.', 'Довольно хороший.']],
    'reach': [['Reach the top.', 'Достигни вершины.']],
    'read': [['Read this book.', 'Прочитай эту книгу.']],
    'ready': [['I am ready.', 'Я готов.']],
    'real': [['A real friend.', 'Настоящий друг.']],
    'realize': [['I realize it now.', 'Я осознаю это сейчас.']],
    'really': [['Really nice.', 'Действительно хороший.']],
    'reason': [['A good reason.', 'Хорошая причина.']],
    'receive': [['Receive a letter.', 'Получи письмо.']],
    'recent': [['A recent photo.', 'Недавнее фото.']],
    'recognize': [['I recognize you.', 'Я узнаю тебя.']],
    'recommend': [['I recommend it.', 'Я рекомендую это.']],
    'record': [['A new record.', 'Новый рекорд.']],
    'red': [['A red rose.', 'Красная роза.']],
    'reduce': [['Reduce the price.', 'Снизь цену.']],
    'refuse': [['Refuse politely.', 'Откажи вежливо.']],
    'regret': [['I regret it.', 'Я сожалею об этом.']],
    'regular': [['A regular customer.', 'Постоянный клиент.']],
    'relative': [['A close relative.', 'Близкий родственник.']],
    'relax': [['Relax and enjoy.', 'Расслабься и наслаждайся.']],
    'remain': [['Remain calm.', 'Оставайся спокойным.']],
    'remember': [['Remember me.', 'Помни меня.']],
    'remind': [['Remind me later.', 'Напомни мне позже.']],
    'remove': [['Remove your shoes.', 'Сними обувь.']],
    'rent': [['Rent a car.', 'Арендуй машину.']],
    'repair': [['Repair the car.', 'Отремонтируй машину.']],
    'repeat': [['Repeat after me.', 'Повторяй за мной.']],
    'reply': [['Reply to me.', 'Ответь мне.']],
    'report': [['Write a report.', 'Напиши отчёт.']],
    'represent': [['Represent your country.', 'Представляй свою страну.']],
    'request': [['A small request.', 'Маленькая просьба.']],
    'require': [['It requires time.', 'Это требует времени.']],
    'research': [['Do research.', 'Проведи исследование.']],
    'reserve': [['Reserve a table.', 'Забронируй столик.']],
    'respect': [['Respect your parents.', 'Уважай родителей.']],
    'rest': [['Take a rest.', 'Отдохни.']],
    'restaurant': [['A nice restaurant.', 'Хороший ресторан.']],
    'result': [['A good result.', 'Хороший результат.']],
    'return': [['Return home.', 'Вернись домой.']],
    'rice': [['Boiled rice.', 'Варёный рис.']],
    'rich': [['A rich man.', 'Богатый человек.']],
    'ride': [['Ride a bike.', 'Кати на велосипеде.']],
    'right': [['Turn right.', 'Поверни направо.']],
    'ring': [['A gold ring.', 'Золотое кольцо.']],
    'rise': [['The sun rises.', 'Солнце встаёт.']],
    'risk': [['A big risk.', 'Большой риск.']],
    'river': [['A wide river.', 'Широкая река.']],
    'road': [['A long road.', 'Длинная дорога.']],
    'rock': [['A heavy rock.', 'Тяжёлый камень.']],
    'role': [['A big role.', 'Большая роль.']],
    'roll': [['Roll the ball.', 'Кати мяч.']],
    'roof': [['A new roof.', 'Новая крыша.']],
    'room': [['A big room.', 'Большая комната.']],
    'root': [['A deep root.', 'Глубокий корень.']],
    'rope': [['A long rope.', 'Длинная верёвка.']],
    'rough': [['A rough road.', 'Грубая дорога.']],
    'round': [['A round table.', 'Круглый стол.']],
    'route': [['A short route.', 'Короткий маршрут.']],
    'row': [['The first row.', 'Первый ряд.']],
    'royal': [['A royal family.', 'Королевская семья.']],
    'rub': [['Rub your hands.', 'Потри руки.']],
    'rubber': [['A rubber ball.', 'Резиновый мяч.']],
    'rude': [['Do not be rude.', 'Не будь грубым.']],
    'ruin': [['Do not ruin it.', 'Не разрушай это.']],
    'rule': [['A simple rule.', 'Простое правило.']],
    'ruler': [['A long ruler.', 'Длинная линейка.']],
    'run': [['Run fast!', 'Беги быстро!']],
    'rush': [['Do not rush.', 'Не спеши.']],

    // ═══ S ═══
    'sad': [['I am sad.', 'Я грустный.']],
    'safe': [['A safe place.', 'Безопасное место.']],
    'safety': [['Safety first.', 'Безопасность прежде всего.']],
    'sail': [['Sail the sea.', 'Плыви по морю.']],
    'salad': [['A fresh salad.', 'Свежий салат.']],
    'salary': [['A good salary.', 'Хорошая зарплата.']],
    'sale': [['A big sale.', 'Большая распродажа.']],
    'salt': [['Add some salt.', 'Добавь соли.']],
    'same': [['The same day.', 'Тот же день.']],
    'sand': [['Warm sand.', 'Тёплый песок.']],
    'sandwich': [['A tasty sandwich.', 'Вкусный бутерброд.']],
    'save': [['Save money.', 'Экономь деньги.']],
    'say': [['Say it again.', 'Скажи это снова.']],
    'scale': [['A small scale.', 'Маленькая шкала.']],
    'scared': [['I am scared.', 'Я напуган.']],
    'scene': [['A beautiful scene.', 'Красивая сцена.']],
    'school': [['Go to school.', 'Иди в школу.']],
    'science': [['Modern science.', 'Современная наука.']],
    'scientist': [['A famous scientist.', 'Известный учёный.']],
    'score': [['A good score.', 'Хороший счёт.']],
    'scream': [['Do not scream.', 'Не кричи.']],
    'screen': [['A big screen.', 'Большой экран.']],
    'sea': [['The blue sea.', 'Синее море.']],
    'search': [['Search for it.', 'Поищи это.']],
    'season': [['A new season.', 'Новый сезон.']],
    'seat': [['Take a seat.', 'Сядь.']],
    'second': [['One second.', 'Одна секунда.']],
    'secret': [['A big secret.', 'Большой секрет.']],
    'secretary': [['A good secretary.', 'Хороший секретарь.']],
    'section': [['A small section.', 'Маленькая секция.']],
    'see': [['I see you.', 'Я тебя вижу.']],
    'seed': [['A small seed.', 'Маленькое семя.']],
    'seem': [['You seem tired.', 'Ты кажешься уставшим.']],
    'sell': [['Sell your car.', 'Продай свою машину.']],
    'send': [['Send a letter.', 'Отправь письмо.']],
    'sense': [['Common sense.', 'Здравый смысл.']],
    'sentence': [['A short sentence.', 'Короткое предложение.']],
    'separate': [['A separate room.', 'Отдельная комната.']],
    'serious': [['A serious problem.', 'Серьёзная проблема.']],
    'serve': [['Serve the food.', 'Подай еду.']],
    'service': [['Good service.', 'Хороший сервис.']],
    'set': [['A full set.', 'Полный набор.']],
    'settle': [['Settle down.', 'Успокойся.']],
    'several': [['Several days.', 'Несколько дней.']],
    'shake': [['Shake my hand.', 'Пожми мою руку.']],
    'shall': [['Shall we go?', 'Пойдём?']],
    'shame': [['What a shame.', 'Как жаль.']],
    'shape': [['A good shape.', 'Хорошая форма.']],
    'share': [['Share your ideas.', 'Поделись идеями.']],
    'sharp': [['A sharp knife.', 'Острый нож.']],
    'shave': [['Shave every morning.', 'Брейся каждое утро.']],
    'she': [['She is my sister.', 'Она моя сестра.']],
    'sheep': [['A white sheep.', 'Белая овца.']],
    'sheet': [['A clean sheet.', 'Чистый лист.']],
    'shelf': [['Put it on the shelf.', 'Положи на полку.']],
    'shell': [['A sea shell.', 'Морская ракушка.']],
    'shine': [['The sun shines.', 'Солнце светит.']],
    'ship': [['A big ship.', 'Большой корабль.']],
    'shirt': [['A white shirt.', 'Белая рубашка.']],
    'shock': [['A big shock.', 'Большой шок.']],
    'shoe': [['A new shoe.', 'Новый ботинок.']],
    'shoot': [['Do not shoot.', 'Не стреляй.']],
    'shop': [['Go to the shop.', 'Иди в магазин.']],
    'shopping': [['Go shopping.', 'Иди за покупками.']],
    'short': [['A short film.', 'Короткий фильм.']],
    'should': [['You should rest.', 'Тебе следует отдохнуть.']],
    'shoulder': [['My shoulder hurts.', 'У меня болит плечо.']],
    'shout': [['Do not shout.', 'Не кричи.']],
    'show': [['Show me the way.', 'Покажи мне дорогу.']],
    'shower': [['Take a shower.', 'Прими душ.']],
    'shut': [['Shut the door.', 'Закрой дверь.']],
    'shy': [['A shy girl.', 'Застенчивая девочка.']],
    'sick': [['I am sick.', 'Я болен.']],
    'side': [['The other side.', 'Другая сторона.']],
    'sight': [['A beautiful sight.', 'Красивый вид.']],
    'sign': [['A road sign.', 'Дорожный знак.']],
    'signal': [['A weak signal.', 'Слабый сигнал.']],
    'silence': [['Total silence.', 'Полная тишина.']],
    'silent': [['A silent night.', 'Тихая ночь.']],
    'silk': [['A silk dress.', 'Шёлковое платье.']],
    'silly': [['A silly joke.', 'Глупая шутка.']],
    'silver': [['A silver ring.', 'Серебряное кольцо.']],
    'similar': [['A similar idea.', 'Похожая идея.']],
    'simple': [['A simple task.', 'Простая задача.']],
    'since': [['Since Monday.', 'С понедельника.']],
    'sing': [['Sing a song.', 'Спой песню.']],
    'singer': [['A famous singer.', 'Известный певец.']],
    'single': [['A single room.', 'Одноместный номер.']],
    'sink': [['A clean sink.', 'Чистая раковина.']],
    'sir': [['Yes, sir.', 'Да, сэр.']],
    'sister': [['My little sister.', 'Моя младшая сестра.']],
    'sit': [['Sit down, please.', 'Сядь, пожалуйста.']],
    'site': [['A good site.', 'Хороший сайт.']],
    'situation': [['A difficult situation.', 'Трудная ситуация.']],
    'six': [['Six months.', 'Шесть месяцев.']],
    'size': [['What size?', 'Какой размер?']],
    'ski': [['Ski in winter.', 'Катись на лыжах зимой.']],
    'skill': [['A useful skill.', 'Полезный навык.']],
    'skin': [['Soft skin.', 'Мягкая кожа.']],
    'skirt': [['A short skirt.', 'Короткая юбка.']],
    'sky': [['The blue sky.', 'Синее небо.']],
    'sleep': [['Sleep well.', 'Спи хорошо.']],
    'slice': [['A slice of bread.', 'Ломтик хлеба.']],
    'slide': [['Slide down.', 'Скатись вниз.']],
    'slight': [['A slight problem.', 'Небольшая проблема.']],
    'slip': [['Do not slip.', 'Не поскользнись.']],
    'slow': [['A slow train.', 'Медленный поезд.']],
    'slowly': [['Speak slowly.', 'Говори медленно.']],
    'small': [['A small house.', 'Маленький дом.']],
    'smart': [['A smart boy.', 'Умный мальчик.']],
    'smell': [['A good smell.', 'Хороший запах.']],
    'smile': [['Smile, please!', 'Улыбнись, пожалуйста!']],
    'smoke': [['Do not smoke.', 'Не кури.']],
    'smooth': [['A smooth surface.', 'Гладкая поверхность.']],
    'snake': [['A long snake.', 'Длинная змея.']],
    'snow': [['White snow.', 'Белый снег.']],
    'so': [['So good.', 'Так хорошо.']],
    'soap': [['A bar of soap.', 'Кусок мыла.']],
    'social': [['Social life.', 'Общественная жизнь.']],
    'society': [['Modern society.', 'Современное общество.']],
    'sock': [['A warm sock.', 'Тёплый носок.']],
    'sofa': [['A soft sofa.', 'Мягкий диван.']],
    'soft': [['Soft hair.', 'Мягкие волосы.']],
    'software': [['New software.', 'Новое ПО.']],
    'soil': [['Good soil.', 'Хорошая почва.']],
    'soldier': [['A brave soldier.', 'Смелый солдат.']],
    'solid': [['A solid wall.', 'Прочная стена.']],
    'solution': [['A good solution.', 'Хорошее решение.']],
    'solve': [['Solve the problem.', 'Реши проблему.']],
    'some': [['Some water.', 'Немного воды.']],
    'somebody': [['Somebody is here.', 'Кто-то здесь.']],
    'someone': [['Someone called you.', 'Кто-то тебе звонил.']],
    'something': [['Something is wrong.', 'Что-то не так.']],
    'sometimes': [['Sometimes I read.', 'Иногда я читаю.']],
    'somewhere': [['Somewhere far away.', 'Где-то далеко.']],
    'son': [['My son is small.', 'Мой сын маленький.']],
    'song': [['A beautiful song.', 'Красивая песня.']],
    'soon': [['See you soon.', 'До скорого.']],
    'sorry': [['I am sorry.', 'Мне жаль.']],
    'sort': [['A new sort.', 'Новый вид.']],
    'soul': [['A kind soul.', 'Добрая душа.']],
    'sound': [['A strange sound.', 'Странный звук.']],
    'soup': [['Hot soup.', 'Горячий суп.']],
    'south': [['The south wind.', 'Южный ветер.']],
    'space': [['Outer space.', 'Космос.']],
    'speak': [['Speak English.', 'Говори по-английски.']],
    'special': [['A special day.', 'Особый день.']],
    'speech': [['A good speech.', 'Хорошая речь.']],
    'speed': [['High speed.', 'Высокая скорость.']],
    'spell': [['Spell your name.', 'Назови своё имя по буквам.']],
    'spend': [['Spend less.', 'Трать меньше.']],
    'spinach': [['Fresh spinach.', 'Свежий шпинат.']],
    'spirit': [['A strong spirit.', 'Сильный дух.']],
    'spite': [['In spite of.', 'Несмотря на.']],
    'split': [['Split the bill.', 'Раздели счёт.']],
    'spoil': [['Do not spoil it.', 'Не порти это.']],
    'spoon': [['A silver spoon.', 'Серебряная ложка.']],
    'sport': [['I love sport.', 'Я люблю спорт.']],
    'spot': [['A nice spot.', 'Хорошее место.']],
    'spread': [['Spread the butter.', 'Намажь масло.']],
    'spring': [['Early spring.', 'Ранняя весна.']],
    'square': [['A big square.', 'Большая площадь.']],
    'stadium': [['A new stadium.', 'Новый стадион.']],
    'staff': [['A friendly staff.', 'Дружелюбный персонал.']],
    'stage': [['On the stage.', 'На сцене.']],
    'stairs': [['Go up the stairs.', 'Поднимись по лестнице.']],
    'stamp': [['A rare stamp.', 'Редкая марка.']],
    'stand': [['Stand up!', 'Встань!']],
    'standard': [['A high standard.', 'Высокий стандарт.']],
    'star': [['A bright star.', 'Яркая звезда.']],
    'start': [['Start now.', 'Начни сейчас.']],
    'state': [['A big state.', 'Большое государство.']],
    'station': [['A train station.', 'Железнодорожная станция.']],
    'stay': [['Stay here.', 'Оставайся здесь.']],
    'steady': [['A steady hand.', 'Твёрдая рука.']],
    'steak': [['A good steak.', 'Хороший стейк.']],
    'steal': [['Do not steal.', 'Не воруй.']],
    'steam': [['Hot steam.', 'Горячий пар.']],
    'steel': [['Strong steel.', 'Прочная сталь.']],
    'step': [['A small step.', 'Маленький шаг.']],
    'stick': [['A wooden stick.', 'Деревянная палка.']],
    'still': [['Still here.', 'Всё ещё здесь.']],
    'stomach': [['My stomach hurts.', 'У меня болит живот.']],
    'stone': [['A heavy stone.', 'Тяжёлый камень.']],
    'stop': [['Stop the car.', 'Останови машину.']],
    'store': [['A big store.', 'Большой магазин.']],
    'storm': [['A strong storm.', 'Сильный шторм.']],
    'story': [['A good story.', 'Хорошая история.']],
    'stove': [['Turn on the stove.', 'Включи плиту.']],
    'straight': [['Go straight.', 'Иди прямо.']],
    'strange': [['A strange man.', 'Странный человек.']],
    'stranger': [['A stranger came.', 'Пришёл незнакомец.']],
    'street': [['A long street.', 'Длинная улица.']],
    'strength': [['Great strength.', 'Большая сила.']],
    'stress': [['A lot of stress.', 'Много стресса.']],
    'stretch': [['Stretch your legs.', 'Разомни ноги.']],
    'strict': [['A strict teacher.', 'Строгий учитель.']],
    'strike': [['A worker strike.', 'Забастовка рабочих.']],
    'string': [['A long string.', 'Длинная верёвка.']],
    'strong': [['A strong man.', 'Сильный человек.']],
    'structure': [['A simple structure.', 'Простая структура.']],
    'struggle': [['Do not struggle.', 'Не борись.']],
    'student': [['A good student.', 'Хороший студент.']],
    'study': [['Study hard.', 'Учись прилежно.']],
    'stupid': [['A stupid joke.', 'Глупая шутка.']],
    'style': [['A nice style.', 'Хороший стиль.']],
    'subject': [['A school subject.', 'Школьный предмет.']],
    'success': [['Great success.', 'Большой успех.']],
    'successful': [['A successful man.', 'Успешный человек.']],
    'such': [['Such a day.', 'Такой день.']],
    'sudden': [['A sudden change.', 'Внезапная перемена.']],
    'suddenly': [['Suddenly it rained.', 'Внезапно пошёл дождь.']],
    'sugar': [['A little sugar.', 'Немного сахара.']],
    'suggest': [['I suggest this.', 'Я предлагаю это.']],
    'suit': [['A black suit.', 'Чёрный костюм.']],
    'suitable': [['A suitable time.', 'Подходящее время.']],
    'summer': [['Hot summer.', 'Жаркое лето.']],
    'sun': [['The bright sun.', 'Яркое солнце.']],
    'supermarket': [['Go to the supermarket.', 'Иди в супермаркет.']],
    'supper': [['Have supper.', 'Поужинай.']],
    'support': [['Support your friend.', 'Поддержи друга.']],
    'suppose': [['I suppose so.', 'Полагаю, что так.']],
    'sure': [['I am sure.', 'Я уверен.']],
    'surface': [['A smooth surface.', 'Гладкая поверхность.']],
    'surprise': [['A nice surprise.', 'Приятный сюрприз.']],
    'surprised': [['I am surprised.', 'Я удивлён.']],
    'sweet': [['Sweet tea.', 'Сладкий чай.']],
    'swim': [['I can swim.', 'Я умею плавать.']],
    'switch': [['Switch off the light.', 'Выключи свет.']],
    'system': [['A new system.', 'Новая система.']],

    // ═══ T ═══
    'table': [['A wooden table.', 'Деревянный стол.']],
    'tail': [['A long tail.', 'Длинный хвост.']],
    'take': [['Take this book.', 'Возьми эту книгу.']],
    'tale': [['A fairy tale.', 'Волшебная сказка.']],
    'talk': [['Talk to me.', 'Поговори со мной.']],
    'tall': [['A tall tree.', 'Высокое дерево.']],
    'tank': [['A big tank.', 'Большой танк.']],
    'tape': [['A piece of tape.', 'Кусок ленты.']],
    'target': [['A clear target.', 'Ясная цель.']],
    'task': [['An easy task.', 'Простая задача.']],
    'taste': [['Taste the soup.', 'Попробуй суп.']],
    'tax': [['Pay the tax.', 'Заплати налог.']],
    'taxi': [['Take a taxi.', 'Возьми такси.']],
    'tea': [['A cup of tea.', 'Чашка чая.']],
    'teach': [['Teach me.', 'Научи меня.']],
    'teacher': [['A good teacher.', 'Хороший учитель.']],
    'team': [['A strong team.', 'Сильная команда.']],
    'tear': [['A single tear.', 'Одна слеза.']],
    'technology': [['Modern technology.', 'Современная технология.']],
    'telephone': [['Answer the telephone.', 'Ответь на телефон.']],
    'television': [['Watch television.', 'Смотри телевизор.']],
    'tell': [['Tell me the truth.', 'Скажи мне правду.']],
    'temperature': [['High temperature.', 'Высокая температура.']],
    'temporary': [['A temporary job.', 'Временная работа.']],
    'ten': [['Ten minutes.', 'Десять минут.']],
    'tend': [['I tend to agree.', 'Я склонен согласиться.']],
    'tennis': [['Play tennis.', 'Играй в теннис.']],
    'tent': [['A small tent.', 'Маленькая палатка.']],
    'term': [['A short term.', 'Короткий срок.']],
    'terrible': [['A terrible film.', 'Ужасный фильм.']],
    'test': [['Pass the test.', 'Пройди тест.']],
    'text': [['Read the text.', 'Прочитай текст.']],
    'than': [['Better than me.', 'Лучше меня.']],
    'thank': [['Thank you!', 'Спасибо тебе!']],
    'that': [['That is good.', 'Это хорошо.']],
    'the': [['The book is here.', 'Книга здесь.']],
    'theatre': [['Go to the theatre.', 'Иди в театр.']],
    'their': [['Their house is big.', 'Их дом большой.']],
    'them': [['Give it to them.', 'Дай это им.']],
    'themselves': [['They did it themselves.', 'Они сделали это сами.']],
    'then': [['Then we go.', 'Тогда мы идём.']],
    'there': [['There is a cat.', 'Там кошка.']],
    'therefore': [['Therefore, I agree.', 'Поэтому я согласен.']],
    'these': [['These books.', 'Эти книги.']],
    'they': [['They are friends.', 'Они друзья.']],
    'thick': [['A thick book.', 'Толстая книга.']],
    'thin': [['A thin cat.', 'Худая кошка.']],
    'thing': [['A good thing.', 'Хорошая вещь.']],
    'think': [['I think so.', 'Я так думаю.']],
    'third': [['The third day.', 'Третий день.']],
    'thirsty': [['I am thirsty.', 'Я хочу пить.']],
    'this': [['This is my house.', 'Это мой дом.']],
    'those': [['Those books.', 'Те книги.']],
    'though': [['Though it rained.', 'Хотя шёл дождь.']],
    'thought': [['A good thought.', 'Хорошая мысль.']],
    'thousand': [['A thousand years.', 'Тысяча лет.']],
    'three': [['Three apples.', 'Три яблока.']],
    'throat': [['My throat hurts.', 'У меня болит горло.']],
    'through': [['Through the window.', 'Через окно.']],
    'throw': [['Throw the ball.', 'Брось мяч.']],
    'thumb': [['My thumb hurts.', 'У меня болит большой палец.']],
    'ticket': [['Buy a ticket.', 'Купи билет.']],
    'tidy': [['A tidy room.', 'Аккуратная комната.']],
    'tie': [['A blue tie.', 'Синий галстук.']],
    'tight': [['Tight shoes.', 'Тесные туфли.']],
    'till': [['Till tomorrow.', 'До завтра.']],
    'time': [['What time is it?', 'Который час?']],
    'tiny': [['A tiny cat.', 'Крошечная кошка.']],
    'tip': [['A good tip.', 'Хороший совет.']],
    'tired': [['I am tired.', 'Я устал.']],
    'title': [['A good title.', 'Хорошее название.']],
    'to': [['Go to school.', 'Иди в школу.']],
    'today': [['Today is Monday.', 'Сегодня понедельник.']],
    'toe': [['My toe hurts.', 'У меня болит палец на ноге.']],
    'together': [['Work together.', 'Работайте вместе.']],
    'toilet': [['Where is the toilet?', 'Где туалет?']],
    'tomato': [['A red tomato.', 'Красный помидор.']],
    'tomorrow': [['See you tomorrow.', 'До завтра.']],
    'tongue': [['Show your tongue.', 'Покажи язык.']],
    'tonight': [['See you tonight.', 'Увидимся вечером.']],
    'too': [['Me too.', 'Я тоже.']],
    'tool': [['A useful tool.', 'Полезный инструмент.']],
    'tooth': [['A white tooth.', 'Белый зуб.']],
    'top': [['On the top.', 'На вершине.']],
    'total': [['A total price.', 'Общая цена.']],
    'touch': [['Do not touch.', 'Не трогай.']],
    'tour': [['A city tour.', 'Экскурсия по городу.']],
    'towards': [['Towards the door.', 'По направлению к двери.']],
    'towel': [['A clean towel.', 'Чистое полотенце.']],
    'tower': [['A tall tower.', 'Высокая башня.']],
    'town': [['A small town.', 'Маленький городок.']],
    'toy': [['A new toy.', 'Новая игрушка.']],
    'track': [['A long track.', 'Длинный путь.']],
    'tradition': [['An old tradition.', 'Старая традиция.']],
    'traffic': [['Heavy traffic.', 'Сильное движение.']],
    'train': [['Take the train.', 'Сядь на поезд.']],
    'training': [['A training session.', 'Тренировка.']],
    'translate': [['Translate this text.', 'Переведи этот текст.']],
    'travel': [['I love to travel.', 'Я люблю путешествовать.']],
    'treat': [['Treat your friends.', 'Угощай друзей.']],
    'tree': [['A tall tree.', 'Высокое дерево.']],
    'trip': [['A short trip.', 'Короткая поездка.']],
    'trouble': [['A big trouble.', 'Большая проблема.']],
    'trousers': [['New trousers.', 'Новые брюки.']],
    'truck': [['A big truck.', 'Большой грузовик.']],
    'true': [['A true story.', 'Правдивая история.']],
    'trust': [['Trust me.', 'Доверься мне.']],
    'truth': [['Tell the truth.', 'Скажи правду.']],
    'try': [['Try again.', 'Попробуй ещё раз.']],
    'tube': [['A small tube.', 'Маленькая трубка.']],
    'turn': [['Turn left.', 'Поверни налево.']],
    'twice': [['Twice a day.', 'Два раза в день.']],
    'type': [['A new type.', 'Новый тип.']],
    'typical': [['A typical day.', 'Типичный день.']],

    // ═══ U ═══
    'ugly': [['An ugly car.', 'Уродливая машина.']],
    'umbrella': [['Take an umbrella.', 'Возьми зонт.']],
    'uncle': [['My uncle is kind.', 'Мой дядя добрый.']],
    'under': [['Under the table.', 'Под столом.']],
    'understand': [['I understand you.', 'Я тебя понимаю.']],
    'unfortunately': [['Unfortunately, no.', 'К сожалению, нет.']],
    'unhappy': [['I am unhappy.', 'Я несчастен.']],
    'uniform': [['A school uniform.', 'Школьная форма.']],
    'unit': [['A small unit.', 'Маленькая единица.']],
    'university': [['Go to university.', 'Иди в университет.']],
    'unless': [['Unless you try.', 'Если только не попробуешь.']],
    'until': [['Wait until tomorrow.', 'Подожди до завтра.']],
    'unusual': [['An unusual day.', 'Необычный день.']],
    'up': [['Stand up.', 'Встань.']],
    'upset': [['I am upset.', 'Я расстроен.']],
    'upstairs': [['Go upstairs.', 'Поднимись наверх.']],
    'us': [['Come with us.', 'Пойдём с нами.']],
    'use': [['Use a pen.', 'Используй ручку.']],
    'useful': [['A useful book.', 'Полезная книга.']],
    'usual': [['The usual way.', 'Обычный способ.']],
    'usually': [['I usually walk.', 'Я обычно хожу пешком.']],

    // ═══ V ═══
    'vacation': [['Summer vacation.', 'Летние каникулы.']],
    'valley': [['A deep valley.', 'Глубокая долина.']],
    'valuable': [['A valuable gift.', 'Ценный подарок.']],
    'value': [['Great value.', 'Большая ценность.']],
    'van': [['A white van.', 'Белый фургон.']],
    'various': [['Various options.', 'Разные варианты.']],
    'vegetable': [['A fresh vegetable.', 'Свежий овощ.']],
    'vehicle': [['A big vehicle.', 'Большое транспортное средство.']],
    'very': [['Very good.', 'Очень хорошо.']],
    'victory': [['A great victory.', 'Великая победа.']],
    'video': [['A funny video.', 'Смешное видео.']],
    'view': [['A beautiful view.', 'Красивый вид.']],
    'village': [['A small village.', 'Маленькая деревня.']],
    'violin': [['Play the violin.', 'Играй на скрипке.']],
    'visit': [['Visit me.', 'Навести меня.']],
    'visitor': [['An important visitor.', 'Важный посетитель.']],
    'voice': [['A soft voice.', 'Мягкий голос.']],
    'volume': [['A high volume.', 'Высокая громкость.']],
    'vote': [['Vote today.', 'Голосуй сегодня.']],

    // ═══ W ═══
    'wage': [['A good wage.', 'Хорошая зарплата.']],
    'waist': [['A narrow waist.', 'Тонкая талия.']],
    'wait': [['Wait here.', 'Жди здесь.']],
    'waiter': [['A polite waiter.', 'Вежливый официант.']],
    'wake': [['Wake up!', 'Проснись!']],
    'walk': [['Let us walk.', 'Давай погуляем.']],
    'wall': [['A white wall.', 'Белая стена.']],
    'want': [['I want tea.', 'Я хочу чай.']],
    'war': [['A long war.', 'Долгая война.']],
    'warm': [['Warm weather.', 'Тёплая погода.']],
    'warn': [['Warn your friend.', 'Предупреди друга.']],
    'wash': [['Wash your hands.', 'Помой руки.']],
    'waste': [['Do not waste time.', 'Не трать время впустую.']],
    'watch': [['Watch TV.', 'Смотри телевизор.']],
    'water': [['Cold water.', 'Холодная вода.']],
    'wave': [['A big wave.', 'Большая волна.']],
    'way': [['Which way?', 'В какую сторону?']],
    'we': [['We are friends.', 'Мы друзья.']],
    'weak': [['A weak man.', 'Слабый человек.']],
    'wear': [['Wear a coat.', 'Надень пальто.']],
    'weather': [['Nice weather.', 'Хорошая погода.']],
    'wedding': [['A big wedding.', 'Большая свадьба.']],
    'week': [['Next week.', 'На следующей неделе.']],
    'weekend': [['Have a nice weekend!', 'Хороших выходных!']],
    'weight': [['My weight is normal.', 'Мой вес в норме.']],
    'welcome': [['Welcome home!', 'Добро пожаловать домой!']],
    'well': [['I feel well.', 'Я хорошо себя чувствую.']],
    'west': [['The west side.', 'Западная сторона.']],
    'wet': [['Wet clothes.', 'Мокрая одежда.']],
    'what': [['What is this?', 'Что это?']],
    'wheel': [['A big wheel.', 'Большое колесо.']],
    'when': [['When are you free?', 'Когда ты свободен?']],
    'where': [['Where are you?', 'Где ты?']],
    'whether': [['Whether you like it or not.', 'Нравится тебе это или нет.']],
    'which': [['Which one?', 'Который?']],
    'while': [['While I wait.', 'Пока я жду.']],
    'white': [['A white shirt.', 'Белая рубашка.']],
    'who': [['Who is it?', 'Кто это?']],
    'whole': [['The whole day.', 'Весь день.']],
    'why': [['Why not?', 'Почему бы и нет?']],
    'wide': [['A wide road.', 'Широкая дорога.']],
    'wife': [['My wife is kind.', 'Моя жена добрая.']],
    'wild': [['A wild animal.', 'Дикое животное.']],
    'will': [['I will come.', 'Я приду.']],
    'win': [['I will win.', 'Я выиграю.']],
    'wind': [['A strong wind.', 'Сильный ветер.']],
    'window': [['Open the window.', 'Открой окно.']],
    'wine': [['Red wine.', 'Красное вино.']],
    'wing': [['A bird wing.', 'Крыло птицы.']],
    'winner': [['The winner is here.', 'Победитель здесь.']],
    'winter': [['Cold winter.', 'Холодная зима.']],
    'wire': [['A thin wire.', 'Тонкий провод.']],
    'wise': [['A wise man.', 'Мудрый человек.']],
    'wish': [['I wish you luck.', 'Желаю тебе удачи.']],
    'with': [['Come with me.', 'Пойдём со мной.']],
    'within': [['Within an hour.', 'В течение часа.']],
    'without': [['Without sugar.', 'Без сахара.']],
    'woman': [['A kind woman.', 'Добрая женщина.']],
    'wonder': [['I wonder why.', 'Интересно, почему.']],
    'wonderful': [['A wonderful day.', 'Чудесный день.']],
    'wood': [['A wood table.', 'Деревянный стол.']],
    'wool': [['Warm wool.', 'Тёплая шерсть.']],
    'word': [['A kind word.', 'Доброе слово.']],
    'work': [['I go to work.', 'Я иду на работу.']],
    'worker': [['A hard worker.', 'Трудолюбивый работник.']],
    'world': [['The whole world.', 'Весь мир.']],
    'worry': [['Do not worry.', 'Не волнуйся.']],
    'worse': [['Worse than before.', 'Хуже, чем раньше.']],
    'worst': [['The worst day.', 'Худший день.']],
    'worth': [['Worth the price.', 'Стоит цены.']],
    'would': [['I would go.', 'Я бы пошёл.']],
    'wound': [['A deep wound.', 'Глубокая рана.']],
    'wrap': [['Wrap the gift.', 'Заверни подарок.']],
    'write': [['Write a letter.', 'Напиши письмо.']],
    'writer': [['A famous writer.', 'Известный писатель.']],
    'wrong': [['A wrong answer.', 'Неверный ответ.']],

    // ═══ Y ═══
    'yard': [['A big yard.', 'Большой двор.']],
    'year': [['Happy New Year!', 'С Новым годом!']],
    'yellow': [['A yellow sun.', 'Жёлтое солнце.']],
    'yes': [['Yes, please.', 'Да, пожалуйста.']],
    'yesterday': [['Yesterday was Monday.', 'Вчера был понедельник.']],
    'yet': [['Not yet.', 'Ещё нет.']],
    'you': [['You are kind.', 'Ты добрый.']],
    'young': [['A young man.', 'Молодой человек.']],
    'your': [['Your house.', 'Твой дом.']],
    'yours': [['This book is yours.', 'Эта книга твоя.']],
    'yourself': [['Believe in yourself.', 'Верь в себя.']],
    'youth': [['A happy youth.', 'Счастливая молодость.']],

    // ═══ Z ═══
    'zero': [['Zero degrees.', 'Ноль градусов.']],
    'zone': [['A quiet zone.', 'Тихая зона.']],
    'zoo': [['Go to the zoo.', 'Иди в зоопарк.']]
};

// ═══════════════════════════════════════════════
// ВСПОМОГАТЕЛЬНЫЕ
// ═══════════════════════════════════════════════
function shuffle(arr) {
    const a = [...arr];
    for (let i = a.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [a[i], a[j]] = [a[j], a[i]];
    }
    return a;
}

// Получить случайное предложение для слова
function getSentence(word) {
    const en = (word.eng || '').toLowerCase();
    const list = SENTENCES[en];
    if (!list || !list.length) return null;
    const [pair] = shuffle(list);
    return { en: pair[0], ru: pair[1], word };
}

// Проверка: есть ли у слова готовый пример?
function hasSentence(word) {
    const en = (word.eng || '').toLowerCase();
    return !!(SENTENCES[en] && SENTENCES[en].length);
}

// ═══════════════════════════════════════════════
// ГЕНЕРАЦИЯ ПРЕДЛОЖЕНИЙ
// ═══════════════════════════════════════════════
function generateSentence(word) {
    return getSentence(word);
}

function generateSentencesList(words, count = 15) {
    if (!words || !words.length) return [];
    const withSentences = words.filter(w => hasSentence(w));
    if (!withSentences.length) return [];
    const sample = shuffle(withSentences).slice(0, count);
    const result = [];
    for (const w of sample) {
        const s = getSentence(w);
        if (s) result.push(s);
    }
    return result;
}

// ═══════════════════════════════════════════════
// 7 ТИПОВ ВОПРОСОВ
// ═══════════════════════════════════════════════
function getSimilarWords(word, allWords, count = 3) {
    const samePos = allWords.filter(w => w.pos === word.pos && w.eng !== word.eng);
    return shuffle(samePos).slice(0, count);
}

// 1. EN → RU
function qENtoRU(w, others) {
    if (!w.ru) return null;
    const opts = shuffle([w.ru, ...others.map(o => o.ru)]).slice(0, 4);
    return {
        type: 'en2ru',
        q: `Как переводится слово <b>${w.eng}</b>?`,
        correct: w.ru,
        options: opts,
        hint: `${w.tr || ''} · ${w.pos}`,
        word: w
    };
}

// 2. RU → EN
function qRUtoEN(w, others) {
    if (!w.ru) return null;
    const opts = shuffle([w.eng, ...others.map(o => o.eng)]).slice(0, 4);
    return {
        type: 'ru2en',
        q: `Как по-английски «<b>${w.ru}</b>»?`,
        correct: w.eng,
        options: opts,
        hint: w.pos,
        word: w
    };
}

// 3. Транскрипция
function qTranscription(w, others) {
    if (!w.tr) return null;
    const oth = others.filter(o => o.tr);
    if (oth.length < 3) return null;
    return {
        type: 'transcription',
        q: `Какая транскрипция у слова <b>${w.eng}</b>?`,
        correct: w.tr,
        options: shuffle([w.tr, ...oth.slice(0, 3).map(o => o.tr)]),
        hint: w.ru,
        word: w
    };
}

// 4. Часть речи
function qPartOfSpeech(w) {
    const posRu = { noun: 'существительное', verb: 'глагол', adjective: 'прилагательное', adverb: 'наречие' };
    if (!posRu[w.pos]) return null;
    return {
        type: 'pos',
        q: `Какая часть речи у слова <b>${w.eng}</b>?`,
        correct: posRu[w.pos],
        options: shuffle(Object.values(posRu)),
        hint: w.ru,
        word: w
    };
}

// 5. Вставь слово (по готовому предложению)
function qFillBlank(w, others) {
    const s = getSentence(w);
    if (!s) return null;
    const re = new RegExp('\\b' + w.eng.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '\\w*\\b', 'i');
    if (!re.test(s.en)) return null;
    return {
        type: 'fill',
        q: `Вставь пропущенное слово:<br><b>${s.en.replace(re, '___')}</b>`,
        correct: w.eng,
        options: shuffle([w.eng, ...others.slice(0, 3).map(o => o.eng)]),
        hint: s.ru,
        word: w
    };
}

// 6. Перевод предложения EN → RU
function qTranslateSentence(w, others) {
    const s = getSentence(w);
    if (!s) return null;
    const wrong = [];
    for (const o of others.slice(0, 8)) {
        const os = getSentence(o);
        if (os && os.ru !== s.ru) wrong.push(os.ru);
        if (wrong.length >= 3) break;
    }
    if (wrong.length < 3) return null;
    return {
        type: 'sentence-ru',
        q: `Как переводится предложение?<br><b>${s.en}</b>`,
        correct: s.ru,
        options: shuffle([s.ru, ...wrong]),
        hint: `${w.eng} — ${w.ru}`,
        word: w
    };
}

// 7. Найди английский вариант RU → EN
function qChooseSentenceEN(w, others) {
    const s = getSentence(w);
    if (!s) return null;
    const wrong = [];
    for (const o of others.slice(0, 8)) {
        const os = getSentence(o);
        if (os && os.en !== s.en) wrong.push(os.en);
        if (wrong.length >= 3) break;
    }
    if (wrong.length < 3) return null;
    return {
        type: 'sentence-en',
        q: `Как сказать по-английски?<br><b>${s.ru}</b>`,
        correct: s.en,
        options: shuffle([s.en, ...wrong]),
        hint: `${w.eng} — ${w.ru}`,
        word: w
    };
}

const ALL_BUILDERS = [
    qENtoRU, qRUtoEN, qTranscription, qPartOfSpeech,
    qFillBlank, qTranslateSentence, qChooseSentenceEN
];

// ═══════════════════════════════════════════════
// ГЛАВНАЯ — генерация вопросов
// ═══════════════════════════════════════════════
function generateQuiz(words, count = 10) {
    if (!words || !words.length) return [];
    const sample = shuffle(words).slice(0, count * 3);
    const questions = [];
    for (const word of sample) {
        if (questions.length >= count) break;
        const others = getSimilarWords(word, words, 6);
        const types = shuffle([...ALL_BUILDERS]);
        for (const builder of types) {
            try {
                const q = builder(word, others);
                if (q && q.options) {
                    const unique = [...new Set(q.options)];
                    if (unique.length >= 2 && unique.includes(q.correct)) {
                        q.options = shuffle(unique);
                        questions.push(q);
                        break;
                    }
                }
            } catch (e) {}
        }
    }
    return questions;
}

// ═══════════════════════════════════════════════
// ЭКСПОРТ — совместим с текущим index.html
// ═══════════════════════════════════════════════
if (typeof window !== 'undefined') {
    window.quizgen = {
        generateSentence,
        generateQuiz,
        generateSentencesList,
        getSentence,
        hasSentence,
        SENTENCES
    };
    console.log('✅ quizgen.js v11 — предложения из готового списка (' + Object.keys(SENTENCES).length + ' слов)');
}
